# encoding: utf-8
# Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.

module Azure end
module Azure::ARM end
module Azure::ARM::NotificationHubs end

require_relative 'namespaces_properties'
require_relative 'namespaces_resources_item_properties'
require_relative 'namespaces_resources_item_properties_wns_credential0'
require_relative 'namespaces_resources_item_properties_apns_credential0'
require_relative 'namespaces_resources_item_properties_gcm_credential0'
require_relative 'namespaces_resources_item_properties_mpns_credential0'
require_relative 'namespaces_resources_item_properties_adm_credential0'
require_relative 'namespaces_resources_item_properties_baidu_credential0'
require_relative 'namespaces_resources_item_properties_authorization_rules0'
require_relative 'notification_hubs_properties'
require_relative 'notification_hubs_properties_wns_credential0'
require_relative 'notification_hubs_properties_apns_credential0'
require_relative 'notification_hubs_properties_gcm_credential0'
require_relative 'notification_hubs_properties_mpns_credential0'
require_relative 'notification_hubs_properties_adm_credential0'
require_relative 'notification_hubs_properties_baidu_credential0'
require_relative 'notification_hubs_properties_authorization_rules0'
require_relative 'namespaces'
require_relative 'namespaces_resources_item'
require_relative 'notification_hubs'

class Azure::ARM::Template
  def namespace(init=nil,&block)
    conf = Azure::ARM::NotificationHubs::Namespace::Configurator.new self
    conf.create init
    conf.instance_exec(conf.parent,&block) if block
    conf.parent
  end
  def namespaces_resources_item(init=nil,&block)
    conf = Azure::ARM::NotificationHubs::NamespacesResourcesItem::Configurator.new self
    conf.create init
    conf.instance_exec(conf.parent,&block) if block
    conf.parent
  end
  def notification_hub(init=nil,&block)
    conf = Azure::ARM::NotificationHubs::NotificationHub::Configurator.new self
    conf.create init
    conf.instance_exec(conf.parent,&block) if block
    conf.parent
  end
end

