# encoding: utf-8
# Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.

require_relative '../arm/module_definition'
require_relative './module_definition'

module Azure::ARM::NotificationHubs
    #
    # Model object.
    #
    class NotificationHubsPropertiesGcmCredential0 < Azure::ARM::TypeBase

      # @return [String]
      # Microsoft.NotificationHubs/namespaces/notificationHubs: Google API
      # key for authenticating with GCM
      attr_accessor :google_api_key

      # @return [String]
      # Microsoft.NotificationHubs/namespaces/notificationHubs: The GCM
      # endpoint to which our connects. Valid endpoint:
      # https://android.googleapis.com/gcm/send . Other values are invalid.
      attr_accessor :gcm_endpoint

      #
      # Validate the object. Throws ValidationError if validation fails.
      #
      def validate
        # Nothing to validate
      end

      #
      # Serializes given Model object into Ruby Hash.
      # @param object Model object to serialize.
      # @return [Hash] Serialized object in form of Ruby Hash.
      #
      def self.serialize_object(output_object, object)
        Azure::ARM::TypeBase.serialize_object(output_object, object)
        object.validate

        serialized_property = object.google_api_key
        output_object[:googleApiKey] = serialized_property unless serialized_property.nil?

        serialized_property = object.gcm_endpoint
        output_object[:gcmEndpoint] = serialized_property unless serialized_property.nil?

        output_object
      end

      def to_h
        hash = {}
        NotificationHubsPropertiesGcmCredential0.serialize_object(hash,self)
        hash
      end

      def self.ds_properties
        result = Array.new 
        result.push :google_api_key
        result.push :gcm_endpoint
        result
      end

      #
      # Deserializes given Ruby Hash into Model object.
      # @param object [Hash] Ruby Hash object to deserialize.
      # @return [NotificationHubsPropertiesGcmCredential0] Deserialized object.
      #
      def self.deserialize_object(output_object, object)
        return if object.nil?
        conf = Configurator.new
        conf.parent = output_object

        if object.key?(:google_api_key)
          conf.google_api_key object[:google_api_key]
          object.delete :google_api_key
        end

        if object.key?(:gcm_endpoint)
          conf.gcm_endpoint object[:gcm_endpoint]
          object.delete :gcm_endpoint
        end

        output_object
      end

      def get_name_template
        'nhpgc'
        end

      def initialize(parent, init)
        super(parent)
        if init.is_a? Hash
          NotificationHubsPropertiesGcmCredential0.deserialize_object self, init.clone
        end
      end

      # Configuration code
      class Configurator < Azure::ARM::ResourceConfigurator
        attr_accessor :parent
        # @param google_api_key
        #        String
        def google_api_key(props)
          if props.is_a? String or props.is_a? Azure::ARM::Expression
            @parent.google_api_key = props
            return
          end
          @parent.google_api_key
        end
        # @param gcm_endpoint
        #        String
        def gcm_endpoint(props)
          if props.is_a? String or props.is_a? Azure::ARM::Expression
            @parent.gcm_endpoint = props
            return
          end
          @parent.gcm_endpoint
        end
        def create(init=nil,&block)
          @parent = NotificationHubsPropertiesGcmCredential0.new nil, init
          self.instance_exec(@parent,&block) if block
          @parent
        end
      end
      def configure(&block)
        conf = Configurator.new
        conf.parent = self
        conf.instance_exec(self,&block) if block
        self
      end
    end
end
