# encoding: utf-8
# Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.

require_relative '../arm/module_definition'
require_relative './module_definition'

module Azure::ARM::Storage
    #
    # Model object.
    #
    class StorageAccountsProperties < Azure::ARM::TypeBase

      # @return [String] Microsoft.Storage/storageAccounts: The type of this
      # account.
      attr_accessor :account_type

      #
      # Validate the object. Throws ValidationError if validation fails.
      #
      def validate
        # Nothing to validate
      end

      #
      # Serializes given Model object into Ruby Hash.
      # @param object Model object to serialize.
      # @return [Hash] Serialized object in form of Ruby Hash.
      #
      def self.serialize_object(output_object, object)
        Azure::ARM::TypeBase.serialize_object(output_object, object)
        object.validate

        serialized_property = object.account_type
        output_object[:accountType] = serialized_property unless serialized_property.nil?

        output_object
      end

      def to_h
        hash = {}
        StorageAccountsProperties.serialize_object(hash,self)
        hash
      end

      def self.ds_properties
        result = Array.new 
        result.push :account_type
        result
      end

      #
      # Deserializes given Ruby Hash into Model object.
      # @param object [Hash] Ruby Hash object to deserialize.
      # @return [StorageAccountsProperties] Deserialized object.
      #
      def self.deserialize_object(output_object, object)
        return if object.nil?
        conf = Configurator.new
        conf.parent = output_object

        if object.key?(:account_type)
          conf.account_type object[:account_type]
          object.delete :account_type
        end

        output_object
      end

      def get_name_template
        'sap'
        end

      def initialize(parent, init)
        super(parent)
        if init.is_a? Hash
          StorageAccountsProperties.deserialize_object self, init.clone
        end
      end

      # Configuration code
      class Configurator < Azure::ARM::ResourceConfigurator
        attr_accessor :parent
        # @param account_type
        #        String
        def account_type(props)
          if props.is_a? String or props.is_a? Azure::ARM::Expression
            @parent.account_type = props
            return
          end
          @parent.account_type
        end
        def create(init=nil,&block)
          @parent = StorageAccountsProperties.new nil, init
          self.instance_exec(@parent,&block) if block
          @parent
        end
      end
      def configure(&block)
        conf = Configurator.new
        conf.parent = self
        conf.instance_exec(self,&block) if block
        self
      end
    end
end
