# encoding: utf-8
# Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.

require_relative '../arm/module_definition'
require_relative './module_definition'

module Azure::ARM::Network
    #
    # Model object.
    #
    class AddressSpace < Azure::ARM::TypeBase

      # @return [Array<String>]
      attr_writer :address_prefixes
      def address_prefixes(name=nil)
        if name and @address_prefixes and @address_prefixes.is_a? Array
          return @address_prefixes.find { | p | p.name == name } if name.is_a? String
          return @address_prefixes[name] if name.is_a? Integer
        end
        @address_prefixes
      end

      #
      # Validate the object. Throws ValidationError if validation fails.
      #
      def validate
        fail ArgumentError, 'property address_prefixes is nil' if @address_prefixes.nil?
        @address_prefixes.each{ |e| e.validate if e.respond_to?(:validate) } unless @address_prefixes.nil?
      end

      #
      # Serializes given Model object into Ruby Hash.
      # @param object Model object to serialize.
      # @return [Hash] Serialized object in form of Ruby Hash.
      #
      def self.serialize_object(output_object, object)
        Azure::ARM::TypeBase.serialize_object(output_object, object)
        object.validate

        serialized_property = object.address_prefixes
        output_object[:addressPrefixes] = serialized_property unless serialized_property.nil?

        output_object
      end

      def to_h
        hash = {}
        AddressSpace.serialize_object(hash,self)
        hash
      end

      def self.ds_properties
        result = Array.new 
        result.push :address_prefixes
        result
      end

      #
      # Deserializes given Ruby Hash into Model object.
      # @param object [Hash] Ruby Hash object to deserialize.
      # @return [AddressSpace] Deserialized object.
      #
      def self.deserialize_object(output_object, object)
        return if object.nil?
        conf = Configurator.new
        conf.parent = output_object

        if object.key?(:address_prefixes)
          conf.address_prefixes object[:address_prefixes]
          object.delete :address_prefixes
        end

        output_object
      end

      def get_name_template
        'as'
        end

      def initialize(parent, init)
        super(parent)
        if init.is_a? Hash
          AddressSpace.deserialize_object self, init.clone
        end
      end

      # Configuration code
      class Configurator < Azure::ARM::ResourceConfigurator
        attr_accessor :parent
        # @param address_prefixes
        #        Array<String>
        def address_prefixes(props)
          if props.is_a? Array
            @parent.address_prefixes = Array.new if @parent.address_prefixes.nil?
            props.each { |p| @parent.address_prefixes.push _address_prefixes_string(p) }
            return @parent.address_prefixes
          end
          _element = nil
          if props.is_a? String or props.is_a? Azure::ARM::Expression
            _element = props
            return
          end
          unless _element.nil?
            @parent.address_prefixes = Array.new if @parent.address_prefixes.nil?
            @parent.address_prefixes.push _element
          end
          @parent.address_prefixes
        end
        def _address_prefixes_string(props)
          if props.is_a? String or props.is_a? Azure::ARM::Expression
            return props
          end
        end
        def create(init=nil,&block)
          @parent = AddressSpace.new nil, init
          self.instance_exec(@parent,&block) if block
          @parent
        end
      end
      def configure(&block)
        conf = Configurator.new
        conf.parent = self
        conf.instance_exec(self,&block) if block
        self
      end
    end
end
