# encoding: utf-8
# Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.

require_relative '../arm/module_definition'
require_relative './module_definition'

module Azure::ARM::Network
    #
    # Model object.
    #
    class FrontendIPConfigurationsExternalProperties < Azure::ARM::TypeBase

      # @return [Id]
      attr_accessor :public_ipaddress

      #
      # Validate the object. Throws ValidationError if validation fails.
      #
      def validate
        fail ArgumentError, 'property public_ipaddress is nil' if @public_ipaddress.nil?
        @public_ipaddress.validate unless @public_ipaddress.nil?
      end

      #
      # Serializes given Model object into Ruby Hash.
      # @param object Model object to serialize.
      # @return [Hash] Serialized object in form of Ruby Hash.
      #
      def self.serialize_object(output_object, object)
        Azure::ARM::TypeBase.serialize_object(output_object, object)
        object.validate

        serialized_property = object.public_ipaddress
        unless serialized_property.nil?
          serialized_property = serialized_property.to_h
        end
        output_object[:publicIPAddress] = serialized_property unless serialized_property.nil?

        output_object
      end

      def to_h
        hash = {}
        FrontendIPConfigurationsExternalProperties.serialize_object(hash,self)
        hash
      end

      def self.ds_properties
        result = Array.new 
        result.push :public_ipaddress
        result
      end

      #
      # Deserializes given Ruby Hash into Model object.
      # @param object [Hash] Ruby Hash object to deserialize.
      # @return [FrontendIPConfigurationsExternalProperties] Deserialized
      # object.
      #
      def self.deserialize_object(output_object, object)
        return if object.nil?
        conf = Configurator.new
        conf.parent = output_object

        if object.key?(:public_ipaddress)
          conf.public_ipaddress object[:public_ipaddress]
          object.delete :public_ipaddress
        end

        output_object
      end

      def get_name_template
        'fipcep'
        end

      def initialize(parent, init)
        super(parent)
        if init.is_a? Hash
          FrontendIPConfigurationsExternalProperties.deserialize_object self, init.clone
        end
      end

      # Configuration code
      class Configurator < Azure::ARM::ResourceConfigurator
        attr_accessor :parent
        # @param public_ipaddress
        #        Id
        def public_ipaddress(props)
          if @parent.public_ipaddress.nil? and props.is_a? Id
            @parent.public_ipaddress = props
            @parent.public_ipaddress.parent = @parent
            @parent.public_ipaddress._rsrcpath = 'publicIPAddress'
          end
          if @parent.public_ipaddress.nil? and (props.is_a? Hash) and (Azure::ARM::TypeBase.matches_type props, Id)
            @parent.public_ipaddress = Id.new(@parent, props)
            @parent.public_ipaddress._rsrcpath = 'publicIPAddress'
          end
          if @parent.public_ipaddress.nil? and (props.respond_to? :to_rsrcid)
            @parent.public_ipaddress = Id.new(@parent, id: props.to_rsrcid.to_s)
            if props.is_a? Azure::ARM::TypeBase and !props.containing_resource.nil?
              @parent.containing_resource.add_dependency props.containing_resource
            end
          end
          @parent.public_ipaddress
        end
        def create(init=nil,&block)
          @parent = FrontendIPConfigurationsExternalProperties.new nil, init
          self.instance_exec(@parent,&block) if block
          @parent
        end
      end
      def configure(&block)
        conf = Configurator.new
        conf.parent = self
        conf.instance_exec(self,&block) if block
        self
      end
    end
end
