# encoding: utf-8
# Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.

require_relative '../arm/module_definition'
require_relative './module_definition'

module Azure::ARM::Network
    #
    # Microsoft.Network/loadBalancers
    #
    class LoadBalancer < Azure::ARM::ResourceBase

      # @return [LoadBalancersProperties]
      attr_accessor :properties

      #
      # Validate the object. Throws ValidationError if validation fails.
      #
      def validate
        fail ArgumentError, 'property type is nil' if self.type.nil?
        fail ArgumentError, 'property api_version is nil' if self.api_version.nil?
        fail ArgumentError, 'property name is nil' if self.name.nil?
        fail ArgumentError, 'property properties is nil' if self.properties.nil?
        @properties.validate unless @properties.nil?
      end

      #
      # Serializes given Model object into Ruby Hash.
      # @param object Model object to serialize.
      # @return [Hash] Serialized object in form of Ruby Hash.
      #
      def self.serialize_object(output_object, object)
        Azure::ARM::ResourceBase.serialize_object(output_object, object)
        object.validate

        serialized_property = object.properties
        unless serialized_property.nil?
          serialized_property = serialized_property.to_h
        end
        output_object[:properties] = serialized_property unless serialized_property.nil?

        output_object
      end

      def to_h
        self.validate
        hash = {}
        LoadBalancer.serialize_object(hash,self)
        hash
      end

      def self.ds_properties
        result = Array.new
        result.push :properties
        result
      end

      #
      # Deserializes given Ruby Hash into Model object.
      # @param object [Hash] Ruby Hash object to deserialize.
      # @return [LoadBalancer] Deserialized object.
      #
      def self.deserialize_object(output_object, object)
        return if object.nil?
        object.delete :name
        object.delete :type
        object.delete :api_version
        object.delete :location
        object.delete :tags
        object.delete :copy
        object.delete :comments
        conf = Configurator.new output_object.template
        conf.parent = output_object

        if object.key?(:properties)
          conf.properties object[:properties]
        end

        unless object.key?(:properties)
          conf.properties object
        end

        output_object
      end

      def get_name_template
        'lb'
      end

      def initialize(parent, init)
        super(parent, init)
        self.type = 'Microsoft.Network/loadBalancers' if self.type.nil?
        self.api_version = '2016-03-30' if self.api_version.nil?
        if init.is_a? Hash
          LoadBalancer.deserialize_object self, init.clone
        end 
      end

      # Configuration code
      class Configurator < Azure::ARM::ResourceConfigurator
        attr_accessor :parent
        attr_accessor :template
        # @param api_version
        #        A string, one of '2015-05-01-preview','2015-06-15','2016-03-30'
        def api_version(props)
          if props.is_a? String
            fail ArgumentError, "#{props} is an invalid value for @parent.api_version" unless ['2015-05-01-preview','2015-06-15','2016-03-30'].index(props)
            @parent.api_version = props
            return
          end
          @parent.api_version
        end
        # @param name
        #        String
        def name(props)
          if props.is_a? String or props.is_a? Azure::ARM::Expression
            @parent.name = props
            return
          end
          @parent.name
        end
        # @param properties
        #        LoadBalancersProperties
        def properties(props)
          if @parent.properties.nil? and props.is_a? LoadBalancersProperties
            @parent.properties = props
            @parent.properties.parent = @parent
            @parent.properties._rsrcpath = 'properties'
          end
          if @parent.properties.nil? and (props.is_a? Hash) and (Azure::ARM::TypeBase.matches_type props, LoadBalancersProperties)
            @parent.properties = LoadBalancersProperties.new(@parent, props)
            @parent.properties._rsrcpath = 'properties'
          end
          @parent.properties
        end
        # @param frontend_ipconfigurations
        #        Array<FrontendIPConfigurations>
        #        Expression
        def frontend_ipconfigurations(props)
          @parent.properties = (LoadBalancersProperties.new @parent, nil) if @parent.properties.nil?
          if props.is_a? Array
            @parent.properties.frontend_ipconfigurations = Array.new if @parent.properties.frontend_ipconfigurations.nil?
            props.each { |p| @parent.properties.frontend_ipconfigurations.push _frontend_ipconfigurations_frontendipconfigurations(p) }
            return @parent.properties.frontend_ipconfigurations
          end
          _element = nil
          if _element.nil? and props.is_a? FrontendIPConfigurations
            _element = props
            _element.parent = @parent
            _element._rsrcpath = 'frontendIPConfigurations'
          end
          if _element.nil? and (props.is_a? Hash) and (Azure::ARM::TypeBase.matches_type props, FrontendIPConfigurations)
            _element = FrontendIPConfigurations.new(@parent, props)
            _element._rsrcpath = 'frontendIPConfigurations'
          end
          if _element.nil?
            _properties = nil
            if _properties.nil? and props.is_a? FrontendIPConfigurationsProperties
              _properties = props
              _properties.parent = @parent
              _properties._rsrcpath = 'frontendIPConfigurations'
            end
            if _properties.nil? and (props.is_a? Hash) and (Azure::ARM::TypeBase.matches_type props, FrontendIPConfigurationsProperties)
              _properties = FrontendIPConfigurationsProperties.new(@parent, props)
              _properties._rsrcpath = 'frontendIPConfigurations'
            end
            unless _properties.nil?
              props[:properties] = _properties
              _element = FrontendIPConfigurations.new(@parent, props)
              _element._rsrcpath = 'frontendIPConfigurations'
              _element.properties = _properties
              _properties.parent = _element
            end
          end
          unless _element.nil?
            @parent.properties.frontend_ipconfigurations = Array.new if @parent.properties.frontend_ipconfigurations.nil?
            @parent.properties.frontend_ipconfigurations.push _element
          end
          if @parent.properties.frontend_ipconfigurations.nil? and props.is_a? Azure::ARM::Expression
            @parent.properties.frontend_ipconfigurations = props
          end
          @parent.properties.frontend_ipconfigurations
        end
        def _frontend_ipconfigurations_frontendipconfigurations(props)
          if props.is_a? FrontendIPConfigurations
            props.parent = @parent
            props._rsrcpath = 'frontendIPConfigurations'
            return props
          end
          if (props.is_a? Hash) and (Azure::ARM::TypeBase.matches_type props, FrontendIPConfigurations)
            _properties = FrontendIPConfigurations.new(@parent, props)
            _properties._rsrcpath = 'frontendIPConfigurations'
            return _properties
          end
          _properties = nil
          if _properties.nil? and props.is_a? FrontendIPConfigurationsProperties
            _properties = props
            _properties.parent = @parent
            _properties._rsrcpath = 'frontendIPConfigurations'
          end
          if _properties.nil? and (props.is_a? Hash) and (Azure::ARM::TypeBase.matches_type props, FrontendIPConfigurationsProperties)
            _properties = FrontendIPConfigurationsProperties.new(@parent, props)
            _properties._rsrcpath = 'frontendIPConfigurations'
          end
          unless _properties.nil?
            props[:properties] = _properties
            frontend_ipconfigurations = FrontendIPConfigurations.new(@parent, props)
            frontend_ipconfigurations._rsrcpath = 'frontendIPConfigurations'
            frontend_ipconfigurations.properties = _properties
            _properties.parent = frontend_ipconfigurations
            return frontend_ipconfigurations
          end
        end
        # @param backend_address_pools
        #        Array<BackendAddressPools>
        #        Expression
        def backend_address_pools(props)
          @parent.properties = (LoadBalancersProperties.new @parent, nil) if @parent.properties.nil?
          if props.is_a? Array
            @parent.properties.backend_address_pools = Array.new if @parent.properties.backend_address_pools.nil?
            props.each { |p| @parent.properties.backend_address_pools.push _backend_address_pools_backendaddresspools(p) }
            return @parent.properties.backend_address_pools
          end
          _element = nil
          if _element.nil? and props.is_a? BackendAddressPools
            _element = props
            _element.parent = @parent
            _element._rsrcpath = 'backendAddressPools'
          end
          if _element.nil? and (props.is_a? Hash) and (Azure::ARM::TypeBase.matches_type props, BackendAddressPools)
            _element = BackendAddressPools.new(@parent, props)
            _element._rsrcpath = 'backendAddressPools'
          end
          unless _element.nil?
            @parent.properties.backend_address_pools = Array.new if @parent.properties.backend_address_pools.nil?
            @parent.properties.backend_address_pools.push _element
          end
          if @parent.properties.backend_address_pools.nil? and props.is_a? Azure::ARM::Expression
            @parent.properties.backend_address_pools = props
          end
          @parent.properties.backend_address_pools
        end
        def _backend_address_pools_backendaddresspools(props)
          if props.is_a? BackendAddressPools
            props.parent = @parent
            props._rsrcpath = 'backendAddressPools'
            return props
          end
          if (props.is_a? Hash) and (Azure::ARM::TypeBase.matches_type props, BackendAddressPools)
            _properties = BackendAddressPools.new(@parent, props)
            _properties._rsrcpath = 'backendAddressPools'
            return _properties
          end
        end
        # @param load_balancing_rules
        #        Array<LoadBalancingRules>
        #        Expression
        def load_balancing_rules(props)
          @parent.properties = (LoadBalancersProperties.new @parent, nil) if @parent.properties.nil?
          if props.is_a? Array
            @parent.properties.load_balancing_rules = Array.new if @parent.properties.load_balancing_rules.nil?
            props.each { |p| @parent.properties.load_balancing_rules.push _load_balancing_rules_loadbalancingrules(p) }
            return @parent.properties.load_balancing_rules
          end
          _element = nil
          if _element.nil? and props.is_a? LoadBalancingRules
            _element = props
            _element.parent = @parent
            _element._rsrcpath = 'loadBalancingRules'
          end
          if _element.nil? and (props.is_a? Hash) and (Azure::ARM::TypeBase.matches_type props, LoadBalancingRules)
            _element = LoadBalancingRules.new(@parent, props)
            _element._rsrcpath = 'loadBalancingRules'
          end
          if _element.nil?
            _properties = nil
            if _properties.nil? and props.is_a? LoadBalancingRulesProperties
              _properties = props
              _properties.parent = @parent
              _properties._rsrcpath = 'loadBalancingRules'
            end
            if _properties.nil? and (props.is_a? Hash) and (Azure::ARM::TypeBase.matches_type props, LoadBalancingRulesProperties)
              _properties = LoadBalancingRulesProperties.new(@parent, props)
              _properties._rsrcpath = 'loadBalancingRules'
            end
            unless _properties.nil?
              props[:properties] = _properties
              _element = LoadBalancingRules.new(@parent, props)
              _element._rsrcpath = 'loadBalancingRules'
              _element.properties = _properties
              _properties.parent = _element
            end
          end
          unless _element.nil?
            @parent.properties.load_balancing_rules = Array.new if @parent.properties.load_balancing_rules.nil?
            @parent.properties.load_balancing_rules.push _element
          end
          if @parent.properties.load_balancing_rules.nil? and props.is_a? Azure::ARM::Expression
            @parent.properties.load_balancing_rules = props
          end
          @parent.properties.load_balancing_rules
        end
        def _load_balancing_rules_loadbalancingrules(props)
          if props.is_a? LoadBalancingRules
            props.parent = @parent
            props._rsrcpath = 'loadBalancingRules'
            return props
          end
          if (props.is_a? Hash) and (Azure::ARM::TypeBase.matches_type props, LoadBalancingRules)
            _properties = LoadBalancingRules.new(@parent, props)
            _properties._rsrcpath = 'loadBalancingRules'
            return _properties
          end
          _properties = nil
          if _properties.nil? and props.is_a? LoadBalancingRulesProperties
            _properties = props
            _properties.parent = @parent
            _properties._rsrcpath = 'loadBalancingRules'
          end
          if _properties.nil? and (props.is_a? Hash) and (Azure::ARM::TypeBase.matches_type props, LoadBalancingRulesProperties)
            _properties = LoadBalancingRulesProperties.new(@parent, props)
            _properties._rsrcpath = 'loadBalancingRules'
          end
          unless _properties.nil?
            props[:properties] = _properties
            load_balancing_rules = LoadBalancingRules.new(@parent, props)
            load_balancing_rules._rsrcpath = 'loadBalancingRules'
            load_balancing_rules.properties = _properties
            _properties.parent = load_balancing_rules
            return load_balancing_rules
          end
        end
        # @param probes
        #        Array<Probes>
        #        Expression
        def probes(props)
          @parent.properties = (LoadBalancersProperties.new @parent, nil) if @parent.properties.nil?
          if props.is_a? Array
            @parent.properties.probes = Array.new if @parent.properties.probes.nil?
            props.each { |p| @parent.properties.probes.push _probes_probes(p) }
            return @parent.properties.probes
          end
          _element = nil
          if _element.nil? and props.is_a? Probes
            _element = props
            _element.parent = @parent
            _element._rsrcpath = 'probes'
          end
          if _element.nil? and (props.is_a? Hash) and (Azure::ARM::TypeBase.matches_type props, Probes)
            _element = Probes.new(@parent, props)
            _element._rsrcpath = 'probes'
          end
          if _element.nil?
            _properties = nil
            if _properties.nil? and props.is_a? ProbeProperties
              _properties = props
              _properties.parent = @parent
              _properties._rsrcpath = 'probes'
            end
            if _properties.nil? and (props.is_a? Hash) and (Azure::ARM::TypeBase.matches_type props, ProbeProperties)
              _properties = ProbeProperties.new(@parent, props)
              _properties._rsrcpath = 'probes'
            end
            unless _properties.nil?
              props[:properties] = _properties
              _element = Probes.new(@parent, props)
              _element._rsrcpath = 'probes'
              _element.properties = _properties
              _properties.parent = _element
            end
          end
          unless _element.nil?
            @parent.properties.probes = Array.new if @parent.properties.probes.nil?
            @parent.properties.probes.push _element
          end
          if @parent.properties.probes.nil? and props.is_a? Azure::ARM::Expression
            @parent.properties.probes = props
          end
          @parent.properties.probes
        end
        def _probes_probes(props)
          if props.is_a? Probes
            props.parent = @parent
            props._rsrcpath = 'probes'
            return props
          end
          if (props.is_a? Hash) and (Azure::ARM::TypeBase.matches_type props, Probes)
            _properties = Probes.new(@parent, props)
            _properties._rsrcpath = 'probes'
            return _properties
          end
          _properties = nil
          if _properties.nil? and props.is_a? ProbeProperties
            _properties = props
            _properties.parent = @parent
            _properties._rsrcpath = 'probes'
          end
          if _properties.nil? and (props.is_a? Hash) and (Azure::ARM::TypeBase.matches_type props, ProbeProperties)
            _properties = ProbeProperties.new(@parent, props)
            _properties._rsrcpath = 'probes'
          end
          unless _properties.nil?
            props[:properties] = _properties
            probes = Probes.new(@parent, props)
            probes._rsrcpath = 'probes'
            probes.properties = _properties
            _properties.parent = probes
            return probes
          end
        end
        # @param inbound_nat_rules
        #        Array<InboundNatRules>
        #        Expression
        def inbound_nat_rules(props)
          @parent.properties = (LoadBalancersProperties.new @parent, nil) if @parent.properties.nil?
          if props.is_a? Array
            @parent.properties.inbound_nat_rules = Array.new if @parent.properties.inbound_nat_rules.nil?
            props.each { |p| @parent.properties.inbound_nat_rules.push _inbound_nat_rules_inboundnatrules(p) }
            return @parent.properties.inbound_nat_rules
          end
          _element = nil
          if _element.nil? and props.is_a? InboundNatRules
            _element = props
            _element.parent = @parent
            _element._rsrcpath = 'inboundNatRules'
          end
          if _element.nil? and (props.is_a? Hash) and (Azure::ARM::TypeBase.matches_type props, InboundNatRules)
            _element = InboundNatRules.new(@parent, props)
            _element._rsrcpath = 'inboundNatRules'
          end
          if _element.nil?
            _properties = nil
            if _properties.nil? and props.is_a? InboundNatRulesProperties
              _properties = props
              _properties.parent = @parent
              _properties._rsrcpath = 'inboundNatRules'
            end
            if _properties.nil? and (props.is_a? Hash) and (Azure::ARM::TypeBase.matches_type props, InboundNatRulesProperties)
              _properties = InboundNatRulesProperties.new(@parent, props)
              _properties._rsrcpath = 'inboundNatRules'
            end
            unless _properties.nil?
              props[:properties] = _properties
              _element = InboundNatRules.new(@parent, props)
              _element._rsrcpath = 'inboundNatRules'
              _element.properties = _properties
              _properties.parent = _element
            end
          end
          unless _element.nil?
            @parent.properties.inbound_nat_rules = Array.new if @parent.properties.inbound_nat_rules.nil?
            @parent.properties.inbound_nat_rules.push _element
          end
          if @parent.properties.inbound_nat_rules.nil? and props.is_a? Azure::ARM::Expression
            @parent.properties.inbound_nat_rules = props
          end
          @parent.properties.inbound_nat_rules
        end
        def _inbound_nat_rules_inboundnatrules(props)
          if props.is_a? InboundNatRules
            props.parent = @parent
            props._rsrcpath = 'inboundNatRules'
            return props
          end
          if (props.is_a? Hash) and (Azure::ARM::TypeBase.matches_type props, InboundNatRules)
            _properties = InboundNatRules.new(@parent, props)
            _properties._rsrcpath = 'inboundNatRules'
            return _properties
          end
          _properties = nil
          if _properties.nil? and props.is_a? InboundNatRulesProperties
            _properties = props
            _properties.parent = @parent
            _properties._rsrcpath = 'inboundNatRules'
          end
          if _properties.nil? and (props.is_a? Hash) and (Azure::ARM::TypeBase.matches_type props, InboundNatRulesProperties)
            _properties = InboundNatRulesProperties.new(@parent, props)
            _properties._rsrcpath = 'inboundNatRules'
          end
          unless _properties.nil?
            props[:properties] = _properties
            inbound_nat_rules = InboundNatRules.new(@parent, props)
            inbound_nat_rules._rsrcpath = 'inboundNatRules'
            inbound_nat_rules.properties = _properties
            _properties.parent = inbound_nat_rules
            return inbound_nat_rules
          end
        end
        # @param inbound_nat_pools
        #        Array<InboundNatPools>
        #        Expression
        def inbound_nat_pools(props)
          @parent.properties = (LoadBalancersProperties.new @parent, nil) if @parent.properties.nil?
          if props.is_a? Array
            @parent.properties.inbound_nat_pools = Array.new if @parent.properties.inbound_nat_pools.nil?
            props.each { |p| @parent.properties.inbound_nat_pools.push _inbound_nat_pools_inboundnatpools(p) }
            return @parent.properties.inbound_nat_pools
          end
          _element = nil
          if _element.nil? and props.is_a? InboundNatPools
            _element = props
            _element.parent = @parent
            _element._rsrcpath = 'inboundNatPools'
          end
          if _element.nil? and (props.is_a? Hash) and (Azure::ARM::TypeBase.matches_type props, InboundNatPools)
            _element = InboundNatPools.new(@parent, props)
            _element._rsrcpath = 'inboundNatPools'
          end
          if _element.nil?
            _properties = nil
            if _properties.nil? and props.is_a? InboundNatPoolsProperties
              _properties = props
              _properties.parent = @parent
              _properties._rsrcpath = 'inboundNatPools'
            end
            if _properties.nil? and (props.is_a? Hash) and (Azure::ARM::TypeBase.matches_type props, InboundNatPoolsProperties)
              _properties = InboundNatPoolsProperties.new(@parent, props)
              _properties._rsrcpath = 'inboundNatPools'
            end
            unless _properties.nil?
              props[:properties] = _properties
              _element = InboundNatPools.new(@parent, props)
              _element._rsrcpath = 'inboundNatPools'
              _element.properties = _properties
              _properties.parent = _element
            end
          end
          unless _element.nil?
            @parent.properties.inbound_nat_pools = Array.new if @parent.properties.inbound_nat_pools.nil?
            @parent.properties.inbound_nat_pools.push _element
          end
          if @parent.properties.inbound_nat_pools.nil? and props.is_a? Azure::ARM::Expression
            @parent.properties.inbound_nat_pools = props
          end
          @parent.properties.inbound_nat_pools
        end
        def _inbound_nat_pools_inboundnatpools(props)
          if props.is_a? InboundNatPools
            props.parent = @parent
            props._rsrcpath = 'inboundNatPools'
            return props
          end
          if (props.is_a? Hash) and (Azure::ARM::TypeBase.matches_type props, InboundNatPools)
            _properties = InboundNatPools.new(@parent, props)
            _properties._rsrcpath = 'inboundNatPools'
            return _properties
          end
          _properties = nil
          if _properties.nil? and props.is_a? InboundNatPoolsProperties
            _properties = props
            _properties.parent = @parent
            _properties._rsrcpath = 'inboundNatPools'
          end
          if _properties.nil? and (props.is_a? Hash) and (Azure::ARM::TypeBase.matches_type props, InboundNatPoolsProperties)
            _properties = InboundNatPoolsProperties.new(@parent, props)
            _properties._rsrcpath = 'inboundNatPools'
          end
          unless _properties.nil?
            props[:properties] = _properties
            inbound_nat_pools = InboundNatPools.new(@parent, props)
            inbound_nat_pools._rsrcpath = 'inboundNatPools'
            inbound_nat_pools.properties = _properties
            _properties.parent = inbound_nat_pools
            return inbound_nat_pools
          end
        end
        # @param outbound_nat_rules
        #        Array<OutboundNatRules>
        #        Expression
        def outbound_nat_rules(props)
          @parent.properties = (LoadBalancersProperties.new @parent, nil) if @parent.properties.nil?
          if props.is_a? Array
            @parent.properties.outbound_nat_rules = Array.new if @parent.properties.outbound_nat_rules.nil?
            props.each { |p| @parent.properties.outbound_nat_rules.push _outbound_nat_rules_outboundnatrules(p) }
            return @parent.properties.outbound_nat_rules
          end
          _element = nil
          if _element.nil? and props.is_a? OutboundNatRules
            _element = props
            _element.parent = @parent
            _element._rsrcpath = 'outboundNatRules'
          end
          if _element.nil? and (props.is_a? Hash) and (Azure::ARM::TypeBase.matches_type props, OutboundNatRules)
            _element = OutboundNatRules.new(@parent, props)
            _element._rsrcpath = 'outboundNatRules'
          end
          if _element.nil?
            _properties = nil
            if _properties.nil? and props.is_a? OutboundNatRulesProperties
              _properties = props
              _properties.parent = @parent
              _properties._rsrcpath = 'outboundNatRules'
            end
            if _properties.nil? and (props.is_a? Hash) and (Azure::ARM::TypeBase.matches_type props, OutboundNatRulesProperties)
              _properties = OutboundNatRulesProperties.new(@parent, props)
              _properties._rsrcpath = 'outboundNatRules'
            end
            unless _properties.nil?
              props[:properties] = _properties
              _element = OutboundNatRules.new(@parent, props)
              _element._rsrcpath = 'outboundNatRules'
              _element.properties = _properties
              _properties.parent = _element
            end
          end
          unless _element.nil?
            @parent.properties.outbound_nat_rules = Array.new if @parent.properties.outbound_nat_rules.nil?
            @parent.properties.outbound_nat_rules.push _element
          end
          if @parent.properties.outbound_nat_rules.nil? and props.is_a? Azure::ARM::Expression
            @parent.properties.outbound_nat_rules = props
          end
          @parent.properties.outbound_nat_rules
        end
        def _outbound_nat_rules_outboundnatrules(props)
          if props.is_a? OutboundNatRules
            props.parent = @parent
            props._rsrcpath = 'outboundNatRules'
            return props
          end
          if (props.is_a? Hash) and (Azure::ARM::TypeBase.matches_type props, OutboundNatRules)
            _properties = OutboundNatRules.new(@parent, props)
            _properties._rsrcpath = 'outboundNatRules'
            return _properties
          end
          _properties = nil
          if _properties.nil? and props.is_a? OutboundNatRulesProperties
            _properties = props
            _properties.parent = @parent
            _properties._rsrcpath = 'outboundNatRules'
          end
          if _properties.nil? and (props.is_a? Hash) and (Azure::ARM::TypeBase.matches_type props, OutboundNatRulesProperties)
            _properties = OutboundNatRulesProperties.new(@parent, props)
            _properties._rsrcpath = 'outboundNatRules'
          end
          unless _properties.nil?
            props[:properties] = _properties
            outbound_nat_rules = OutboundNatRules.new(@parent, props)
            outbound_nat_rules._rsrcpath = 'outboundNatRules'
            outbound_nat_rules.properties = _properties
            _properties.parent = outbound_nat_rules
            return outbound_nat_rules
          end
        end
        def initialize(template)
          @template = template
        end
        def create(init=nil,&block)
          @parent = LoadBalancer.new @template,init
          @template.resources.push @parent
          self.instance_exec(@parent,&block) if block
          @parent
        end
      end
      def configure(&block)
        conf = Configurator.new self.template
        conf.parent = self
        conf.instance_exec(self,&block) if block
        self
      end
    end
end
