# encoding: utf-8
# Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.

require_relative '../arm/module_definition'
require_relative './module_definition'

module Azure::ARM::Network
    #
    # Model object.
    #
    class LoadBalancingRules < Azure::ARM::TypeBase

      # @return [String]
      attr_accessor :name

      # @return [LoadBalancingRulesProperties]
      attr_accessor :properties

      #
      # Validate the object. Throws ValidationError if validation fails.
      #
      def validate
        fail ArgumentError, 'property name is nil' if @name.nil?
        fail ArgumentError, 'property properties is nil' if @properties.nil?
        @properties.validate unless @properties.nil?
      end

      #
      # Serializes given Model object into Ruby Hash.
      # @param object Model object to serialize.
      # @return [Hash] Serialized object in form of Ruby Hash.
      #
      def self.serialize_object(output_object, object)
        Azure::ARM::TypeBase.serialize_object(output_object, object)
        object.validate

        serialized_property = object.name
        output_object[:name] = serialized_property unless serialized_property.nil?

        serialized_property = object.properties
        unless serialized_property.nil?
          serialized_property = serialized_property.to_h
        end
        output_object[:properties] = serialized_property unless serialized_property.nil?

        output_object
      end

      def to_h
        hash = {}
        LoadBalancingRules.serialize_object(hash,self)
        hash
      end

      def self.ds_properties
        result = Array.new 
        result.push :properties
        result
      end

      #
      # Deserializes given Ruby Hash into Model object.
      # @param object [Hash] Ruby Hash object to deserialize.
      # @return [LoadBalancingRules] Deserialized object.
      #
      def self.deserialize_object(output_object, object)
        return if object.nil?
        conf = Configurator.new
        conf.parent = output_object

        if object.key?(:name)
          conf.name object[:name]
          object.delete :name
        end

        if object.key?(:properties)
          conf.properties object[:properties]
        end

                unless object.key?(:properties)
          conf.properties object
        end

        output_object
      end

      def get_name_template
        'lbr'
        end

      def initialize(parent, init)
        super(parent)
        if init.is_a? Hash
          LoadBalancingRules.deserialize_object self, init.clone
        end
      end

      # Configuration code
      class Configurator < Azure::ARM::ResourceConfigurator
        attr_accessor :parent
        # @param name
        #        String
        def name(props)
          if props.is_a? String or props.is_a? Azure::ARM::Expression
            @parent.name = props
            return
          end
          @parent.name
        end
        # @param properties
        #        LoadBalancingRulesProperties
        def properties(props)
          if @parent.properties.nil? and props.is_a? LoadBalancingRulesProperties
            @parent.properties = props
            @parent.properties.parent = @parent
            @parent.properties._rsrcpath = 'properties'
          end
          if @parent.properties.nil? and (props.is_a? Hash) and (Azure::ARM::TypeBase.matches_type props, LoadBalancingRulesProperties)
            @parent.properties = LoadBalancingRulesProperties.new(@parent, props)
            @parent.properties._rsrcpath = 'properties'
          end
          @parent.properties
        end
        # @param frontend_ipconfiguration
        #        Id
        def frontend_ipconfiguration(props)
          @parent.properties = (LoadBalancingRulesProperties.new @parent, nil) if @parent.properties.nil?
          if @parent.properties.frontend_ipconfiguration.nil? and props.is_a? Id
            @parent.properties.frontend_ipconfiguration = props
            @parent.properties.frontend_ipconfiguration.parent = @parent
            @parent.properties.frontend_ipconfiguration._rsrcpath = 'frontendIPConfiguration'
          end
          if @parent.properties.frontend_ipconfiguration.nil? and (props.is_a? Hash) and (Azure::ARM::TypeBase.matches_type props, Id)
            @parent.properties.frontend_ipconfiguration = Id.new(@parent, props)
            @parent.properties.frontend_ipconfiguration._rsrcpath = 'frontendIPConfiguration'
          end
          if @parent.properties.frontend_ipconfiguration.nil? and (props.respond_to? :to_rsrcid)
            @parent.properties.frontend_ipconfiguration = Id.new(@parent, id: props.to_rsrcid.to_s)
            if props.is_a? Azure::ARM::TypeBase and !props.containing_resource.nil?
              @parent.containing_resource.add_dependency props.containing_resource
            end
          end
          @parent.properties.frontend_ipconfiguration
        end
        # @param backend_address_pool
        #        Id
        def backend_address_pool(props)
          @parent.properties = (LoadBalancingRulesProperties.new @parent, nil) if @parent.properties.nil?
          if @parent.properties.backend_address_pool.nil? and props.is_a? Id
            @parent.properties.backend_address_pool = props
            @parent.properties.backend_address_pool.parent = @parent
            @parent.properties.backend_address_pool._rsrcpath = 'backendAddressPool'
          end
          if @parent.properties.backend_address_pool.nil? and (props.is_a? Hash) and (Azure::ARM::TypeBase.matches_type props, Id)
            @parent.properties.backend_address_pool = Id.new(@parent, props)
            @parent.properties.backend_address_pool._rsrcpath = 'backendAddressPool'
          end
          if @parent.properties.backend_address_pool.nil? and (props.respond_to? :to_rsrcid)
            @parent.properties.backend_address_pool = Id.new(@parent, id: props.to_rsrcid.to_s)
            if props.is_a? Azure::ARM::TypeBase and !props.containing_resource.nil?
              @parent.containing_resource.add_dependency props.containing_resource
            end
          end
          @parent.properties.backend_address_pool
        end
        # @param protocol
        #        A string, one of 'Udp','Tcp'
        #        Expression
        def protocol(props)
          @parent.properties = (LoadBalancingRulesProperties.new @parent, nil) if @parent.properties.nil?
          if props.is_a? String
            fail ArgumentError, "#{props} is an invalid value for @parent.properties.protocol" unless ['Udp','Tcp'].index(props)
            @parent.properties.protocol = props
            return
          end
          if @parent.properties.protocol.nil? and props.is_a? Azure::ARM::Expression
            @parent.properties.protocol = props
          end
          @parent.properties.protocol
        end
        # @param frontend_port
        #        Fixnum
        #        Expression
        def frontend_port(props)
          @parent.properties = (LoadBalancingRulesProperties.new @parent, nil) if @parent.properties.nil?
          if props.is_a? Fixnum or props.is_a? Azure::ARM::Expression
            @parent.properties.frontend_port = props
            return
          end
          if @parent.properties.frontend_port.nil? and props.is_a? Azure::ARM::Expression
            @parent.properties.frontend_port = props
          end
          @parent.properties.frontend_port
        end
        # @param backend_port
        #        Fixnum
        #        Expression
        def backend_port(props)
          @parent.properties = (LoadBalancingRulesProperties.new @parent, nil) if @parent.properties.nil?
          if props.is_a? Fixnum or props.is_a? Azure::ARM::Expression
            @parent.properties.backend_port = props
            return
          end
          if @parent.properties.backend_port.nil? and props.is_a? Azure::ARM::Expression
            @parent.properties.backend_port = props
          end
          @parent.properties.backend_port
        end
        # @param probe
        #        Id
        def probe(props)
          @parent.properties = (LoadBalancingRulesProperties.new @parent, nil) if @parent.properties.nil?
          if @parent.properties.probe.nil? and props.is_a? Id
            @parent.properties.probe = props
            @parent.properties.probe.parent = @parent
            @parent.properties.probe._rsrcpath = 'probe'
          end
          if @parent.properties.probe.nil? and (props.is_a? Hash) and (Azure::ARM::TypeBase.matches_type props, Id)
            @parent.properties.probe = Id.new(@parent, props)
            @parent.properties.probe._rsrcpath = 'probe'
          end
          if @parent.properties.probe.nil? and (props.respond_to? :to_rsrcid)
            @parent.properties.probe = Id.new(@parent, id: props.to_rsrcid.to_s)
            if props.is_a? Azure::ARM::TypeBase and !props.containing_resource.nil?
              @parent.containing_resource.add_dependency props.containing_resource
            end
          end
          @parent.properties.probe
        end
        # @param enable_floating_ip
        #        Boolean
        #        Expression
        def enable_floating_ip(props)
          @parent.properties = (LoadBalancingRulesProperties.new @parent, nil) if @parent.properties.nil?
          if props.is_a? TrueClass or props.is_a? FalseClass or props.is_a? Azure::ARM::Expression
            @parent.properties.enable_floating_ip = props
            return
          end
          if @parent.properties.enable_floating_ip.nil? and props.is_a? Azure::ARM::Expression
            @parent.properties.enable_floating_ip = props
          end
          @parent.properties.enable_floating_ip
        end
        # @param idle_timeout_in_minutes
        #        Fixnum
        #        Expression
        def idle_timeout_in_minutes(props)
          @parent.properties = (LoadBalancingRulesProperties.new @parent, nil) if @parent.properties.nil?
          if props.is_a? Fixnum or props.is_a? Azure::ARM::Expression
            @parent.properties.idle_timeout_in_minutes = props
            return
          end
          if @parent.properties.idle_timeout_in_minutes.nil? and props.is_a? Azure::ARM::Expression
            @parent.properties.idle_timeout_in_minutes = props
          end
          @parent.properties.idle_timeout_in_minutes
        end
        # @param load_distribution
        #        A string, one of 'Default','SourceIP','SourceIPProtocol'
        #        Expression
        def load_distribution(props)
          @parent.properties = (LoadBalancingRulesProperties.new @parent, nil) if @parent.properties.nil?
          if props.is_a? String
            fail ArgumentError, "#{props} is an invalid value for @parent.properties.load_distribution" unless ['Default','SourceIP','SourceIPProtocol'].index(props)
            @parent.properties.load_distribution = props
            return
          end
          if @parent.properties.load_distribution.nil? and props.is_a? Azure::ARM::Expression
            @parent.properties.load_distribution = props
          end
          @parent.properties.load_distribution
        end
        def create(init=nil,&block)
          @parent = LoadBalancingRules.new nil, init
          self.instance_exec(@parent,&block) if block
          @parent
        end
      end
      def configure(&block)
        conf = Configurator.new
        conf.parent = self
        conf.instance_exec(self,&block) if block
        self
      end
    end
end
