# encoding: utf-8
# Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.

require_relative '../arm/module_definition'
require_relative './module_definition'

module Azure::ARM::Network
    #
    # Model object.
    #
    class OutboundNatRulesProperties < Azure::ARM::TypeBase

      # @return [Array<Id>]
      attr_writer :frontend_ipconfigurations
      def frontend_ipconfigurations(name=nil)
        if name and @frontend_ipconfigurations and @frontend_ipconfigurations.is_a? Array
          return @frontend_ipconfigurations.find { | p | p.name == name } if name.is_a? String
          return @frontend_ipconfigurations[name] if name.is_a? Integer
        end
        @frontend_ipconfigurations
      end

      # @return [Id]
      attr_accessor :backend_address_pool

      #
      # Validate the object. Throws ValidationError if validation fails.
      #
      def validate
        fail ArgumentError, 'property frontend_ipconfigurations is nil' if @frontend_ipconfigurations.nil?
        fail ArgumentError, 'property backend_address_pool is nil' if @backend_address_pool.nil?
        @frontend_ipconfigurations.each{ |e| e.validate if e.respond_to?(:validate) } unless @frontend_ipconfigurations.nil?
        @backend_address_pool.validate unless @backend_address_pool.nil?
      end

      #
      # Serializes given Model object into Ruby Hash.
      # @param object Model object to serialize.
      # @return [Hash] Serialized object in form of Ruby Hash.
      #
      def self.serialize_object(output_object, object)
        Azure::ARM::TypeBase.serialize_object(output_object, object)
        object.validate

        serialized_property = object.frontend_ipconfigurations
        unless serialized_property.nil?
          serializedarray = []
          serialized_property.each do |element|
            unless element.nil?
              element = element.to_h
            end
            serializedarray.push(element)
          end
          serialized_property = serializedarray
        end
        output_object[:frontendIPConfigurations] = serialized_property unless serialized_property.nil?

        serialized_property = object.backend_address_pool
        unless serialized_property.nil?
          serialized_property = serialized_property.to_h
        end
        output_object[:backendAddressPool] = serialized_property unless serialized_property.nil?

        output_object
      end

      def to_h
        hash = {}
        OutboundNatRulesProperties.serialize_object(hash,self)
        hash
      end

      def self.ds_properties
        result = Array.new 
        result.push :frontend_ipconfigurations
        result.push :backend_address_pool
        result
      end

      #
      # Deserializes given Ruby Hash into Model object.
      # @param object [Hash] Ruby Hash object to deserialize.
      # @return [OutboundNatRulesProperties] Deserialized object.
      #
      def self.deserialize_object(output_object, object)
        return if object.nil?
        conf = Configurator.new
        conf.parent = output_object

        if object.key?(:frontend_ipconfigurations)
          conf.frontend_ipconfigurations object[:frontend_ipconfigurations]
          object.delete :frontend_ipconfigurations
        end

        if object.key?(:backend_address_pool)
          conf.backend_address_pool object[:backend_address_pool]
          object.delete :backend_address_pool
        end

        output_object
      end

      def get_name_template
        'onrp'
        end

      def initialize(parent, init)
        super(parent)
        if init.is_a? Hash
          OutboundNatRulesProperties.deserialize_object self, init.clone
        end
      end

      # Configuration code
      class Configurator < Azure::ARM::ResourceConfigurator
        attr_accessor :parent
        # @param frontend_ipconfigurations
        #        Array<Id>
        def frontend_ipconfigurations(props)
          if props.is_a? Array
            @parent.frontend_ipconfigurations = Array.new if @parent.frontend_ipconfigurations.nil?
            props.each { |p| @parent.frontend_ipconfigurations.push _frontend_ipconfigurations_id(p) }
            return @parent.frontend_ipconfigurations
          end
          _element = nil
          if _element.nil? and props.is_a? Id
            _element = props
            _element.parent = @parent
            _element._rsrcpath = 'frontendIPConfigurations'
          end
          if _element.nil? and (props.is_a? Hash) and (Azure::ARM::TypeBase.matches_type props, Id)
            _element = Id.new(@parent, props)
            _element._rsrcpath = 'frontendIPConfigurations'
          end
          if _element.nil? and (props.respond_to? :to_rsrcid)
            _element = Id.new(@parent, id: props.to_rsrcid.to_s)
            if props.is_a? Azure::ARM::TypeBase and !props.containing_resource.nil?
              @parent.containing_resource.add_dependency props.containing_resource
            end
          end
          unless _element.nil?
            @parent.frontend_ipconfigurations = Array.new if @parent.frontend_ipconfigurations.nil?
            @parent.frontend_ipconfigurations.push _element
          end
          @parent.frontend_ipconfigurations
        end
        def _frontend_ipconfigurations_id(props)
          if props.is_a? Id
            props.parent = @parent
            props._rsrcpath = 'frontendIPConfigurations'
            return props
          end
          if (props.is_a? Hash) and (Azure::ARM::TypeBase.matches_type props, Id)
            _properties = Id.new(@parent, props)
            _properties._rsrcpath = 'frontendIPConfigurations'
            return _properties
          end
          if props.respond_to? :to_rsrcid
            return Id.new(@parent, id: props.to_rsrcid.to_s)
          end
        end
        # @param backend_address_pool
        #        Id
        def backend_address_pool(props)
          if @parent.backend_address_pool.nil? and props.is_a? Id
            @parent.backend_address_pool = props
            @parent.backend_address_pool.parent = @parent
            @parent.backend_address_pool._rsrcpath = 'backendAddressPool'
          end
          if @parent.backend_address_pool.nil? and (props.is_a? Hash) and (Azure::ARM::TypeBase.matches_type props, Id)
            @parent.backend_address_pool = Id.new(@parent, props)
            @parent.backend_address_pool._rsrcpath = 'backendAddressPool'
          end
          if @parent.backend_address_pool.nil? and (props.respond_to? :to_rsrcid)
            @parent.backend_address_pool = Id.new(@parent, id: props.to_rsrcid.to_s)
            if props.is_a? Azure::ARM::TypeBase and !props.containing_resource.nil?
              @parent.containing_resource.add_dependency props.containing_resource
            end
          end
          @parent.backend_address_pool
        end
        def create(init=nil,&block)
          @parent = OutboundNatRulesProperties.new nil, init
          self.instance_exec(@parent,&block) if block
          @parent
        end
      end
      def configure(&block)
        conf = Configurator.new
        conf.parent = self
        conf.instance_exec(self,&block) if block
        self
      end
    end
end
