# encoding: utf-8
# Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.

require_relative '../arm/module_definition'
require_relative './module_definition'

module Azure::ARM::Network
    #
    # Model object.
    #
    class Probes < Azure::ARM::TypeBase

      # @return [String]
      attr_accessor :name

      # @return [ProbeProperties]
      attr_accessor :properties

      #
      # Validate the object. Throws ValidationError if validation fails.
      #
      def validate
        fail ArgumentError, 'property name is nil' if @name.nil?
        fail ArgumentError, 'property properties is nil' if @properties.nil?
        @properties.validate unless @properties.nil?
      end

      #
      # Serializes given Model object into Ruby Hash.
      # @param object Model object to serialize.
      # @return [Hash] Serialized object in form of Ruby Hash.
      #
      def self.serialize_object(output_object, object)
        Azure::ARM::TypeBase.serialize_object(output_object, object)
        object.validate

        serialized_property = object.name
        output_object[:name] = serialized_property unless serialized_property.nil?

        serialized_property = object.properties
        unless serialized_property.nil?
          serialized_property = serialized_property.to_h
        end
        output_object[:properties] = serialized_property unless serialized_property.nil?

        output_object
      end

      def to_h
        hash = {}
        Probes.serialize_object(hash,self)
        hash
      end

      def self.ds_properties
        result = Array.new 
        result.push :properties
        result
      end

      #
      # Deserializes given Ruby Hash into Model object.
      # @param object [Hash] Ruby Hash object to deserialize.
      # @return [Probes] Deserialized object.
      #
      def self.deserialize_object(output_object, object)
        return if object.nil?
        conf = Configurator.new
        conf.parent = output_object

        if object.key?(:name)
          conf.name object[:name]
          object.delete :name
        end

        if object.key?(:properties)
          conf.properties object[:properties]
        end

                unless object.key?(:properties)
          conf.properties object
        end

        output_object
      end

      def get_name_template
        'p'
        end

      def initialize(parent, init)
        super(parent)
        if init.is_a? Hash
          Probes.deserialize_object self, init.clone
        end
      end

      # Configuration code
      class Configurator < Azure::ARM::ResourceConfigurator
        attr_accessor :parent
        # @param name
        #        String
        def name(props)
          if props.is_a? String or props.is_a? Azure::ARM::Expression
            @parent.name = props
            return
          end
          @parent.name
        end
        # @param properties
        #        ProbeProperties
        def properties(props)
          if @parent.properties.nil? and props.is_a? ProbeProperties
            @parent.properties = props
            @parent.properties.parent = @parent
            @parent.properties._rsrcpath = 'properties'
          end
          if @parent.properties.nil? and (props.is_a? Hash) and (Azure::ARM::TypeBase.matches_type props, ProbeProperties)
            @parent.properties = ProbeProperties.new(@parent, props)
            @parent.properties._rsrcpath = 'properties'
          end
          @parent.properties
        end
        # @param protocol
        #        A string, one of 'Http','Tcp'
        #        Expression
        def protocol(props)
          @parent.properties = (ProbeProperties.new @parent, nil) if @parent.properties.nil?
          if props.is_a? String
            fail ArgumentError, "#{props} is an invalid value for @parent.properties.protocol" unless ['Http','Tcp'].index(props)
            @parent.properties.protocol = props
            return
          end
          if @parent.properties.protocol.nil? and props.is_a? Azure::ARM::Expression
            @parent.properties.protocol = props
          end
          @parent.properties.protocol
        end
        # @param port
        #        Fixnum
        #        Expression
        def port(props)
          @parent.properties = (ProbeProperties.new @parent, nil) if @parent.properties.nil?
          if props.is_a? Fixnum or props.is_a? Azure::ARM::Expression
            @parent.properties.port = props
            return
          end
          if @parent.properties.port.nil? and props.is_a? Azure::ARM::Expression
            @parent.properties.port = props
          end
          @parent.properties.port
        end
        # @param request_path
        #        String
        def request_path(props)
          @parent.properties = (ProbeProperties.new @parent, nil) if @parent.properties.nil?
          if props.is_a? String or props.is_a? Azure::ARM::Expression
            @parent.properties.request_path = props
            return
          end
          @parent.properties.request_path
        end
        # @param interval_in_seconds
        #        Fixnum
        #        Expression
        def interval_in_seconds(props)
          @parent.properties = (ProbeProperties.new @parent, nil) if @parent.properties.nil?
          if props.is_a? Fixnum or props.is_a? Azure::ARM::Expression
            @parent.properties.interval_in_seconds = props
            return
          end
          if @parent.properties.interval_in_seconds.nil? and props.is_a? Azure::ARM::Expression
            @parent.properties.interval_in_seconds = props
          end
          @parent.properties.interval_in_seconds
        end
        # @param number_of_probes
        #        Fixnum
        #        Expression
        def number_of_probes(props)
          @parent.properties = (ProbeProperties.new @parent, nil) if @parent.properties.nil?
          if props.is_a? Fixnum or props.is_a? Azure::ARM::Expression
            @parent.properties.number_of_probes = props
            return
          end
          if @parent.properties.number_of_probes.nil? and props.is_a? Azure::ARM::Expression
            @parent.properties.number_of_probes = props
          end
          @parent.properties.number_of_probes
        end
        def create(init=nil,&block)
          @parent = Probes.new nil, init
          self.instance_exec(@parent,&block) if block
          @parent
        end
      end
      def configure(&block)
        conf = Configurator.new
        conf.parent = self
        conf.instance_exec(self,&block) if block
        self
      end
    end
end
