# encoding: utf-8
# Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.

require_relative '../arm/module_definition'
require_relative './module_definition'

module Azure::ARM::Network
    #
    # Model object.
    #
    class PublicIPAddressDnsSettings < Azure::ARM::TypeBase

      # @return [String]
      attr_accessor :domain_name_label

      # @return [String]
      attr_accessor :reverse_fqdn

      #
      # Validate the object. Throws ValidationError if validation fails.
      #
      def validate
        fail ArgumentError, 'property domain_name_label is nil' if @domain_name_label.nil?
      end

      #
      # Serializes given Model object into Ruby Hash.
      # @param object Model object to serialize.
      # @return [Hash] Serialized object in form of Ruby Hash.
      #
      def self.serialize_object(output_object, object)
        Azure::ARM::TypeBase.serialize_object(output_object, object)
        object.validate

        serialized_property = object.domain_name_label
        output_object[:domainNameLabel] = serialized_property unless serialized_property.nil?

        serialized_property = object.reverse_fqdn
        output_object[:reverseFqdn] = serialized_property unless serialized_property.nil?

        output_object
      end

      def to_h
        hash = {}
        PublicIPAddressDnsSettings.serialize_object(hash,self)
        hash
      end

      def self.ds_properties
        result = Array.new 
        result.push :domain_name_label
        result.push :reverse_fqdn
        result
      end

      #
      # Deserializes given Ruby Hash into Model object.
      # @param object [Hash] Ruby Hash object to deserialize.
      # @return [PublicIPAddressDnsSettings] Deserialized object.
      #
      def self.deserialize_object(output_object, object)
        return if object.nil?
        conf = Configurator.new
        conf.parent = output_object

        if object.key?(:domain_name_label)
          conf.domain_name_label object[:domain_name_label]
          object.delete :domain_name_label
        end

        if object.key?(:reverse_fqdn)
          conf.reverse_fqdn object[:reverse_fqdn]
          object.delete :reverse_fqdn
        end

        output_object
      end

      def get_name_template
        'pipads'
        end

      def initialize(parent, init)
        super(parent)
        if init.is_a? Hash
          PublicIPAddressDnsSettings.deserialize_object self, init.clone
        end
      end

      # Configuration code
      class Configurator < Azure::ARM::ResourceConfigurator
        attr_accessor :parent
        # @param domain_name_label
        #        String
        def domain_name_label(props)
          if props.is_a? String or props.is_a? Azure::ARM::Expression
            @parent.domain_name_label = props
            return
          end
          @parent.domain_name_label
        end
        # @param reverse_fqdn
        #        String
        def reverse_fqdn(props)
          if props.is_a? String or props.is_a? Azure::ARM::Expression
            @parent.reverse_fqdn = props
            return
          end
          @parent.reverse_fqdn
        end
        def create(init=nil,&block)
          @parent = PublicIPAddressDnsSettings.new nil, init
          self.instance_exec(@parent,&block) if block
          @parent
        end
      end
      def configure(&block)
        conf = Configurator.new
        conf.parent = self
        conf.instance_exec(self,&block) if block
        self
      end
    end
end
