# encoding: utf-8
# Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.

require_relative '../arm/module_definition'
require_relative './module_definition'

module Azure::ARM::Network
    #
    # Microsoft.Network/routeTables
    #
    class RouteTable < Azure::ARM::ResourceBase

      # @return [RouteTablesProperties]
      attr_accessor :properties

      #
      # Validate the object. Throws ValidationError if validation fails.
      #
      def validate
        fail ArgumentError, 'property type is nil' if self.type.nil?
        fail ArgumentError, 'property api_version is nil' if self.api_version.nil?
        fail ArgumentError, 'property name is nil' if self.name.nil?
        fail ArgumentError, 'property properties is nil' if self.properties.nil?
        @properties.validate unless @properties.nil?
      end

      #
      # Serializes given Model object into Ruby Hash.
      # @param object Model object to serialize.
      # @return [Hash] Serialized object in form of Ruby Hash.
      #
      def self.serialize_object(output_object, object)
        Azure::ARM::ResourceBase.serialize_object(output_object, object)
        object.validate

        serialized_property = object.properties
        unless serialized_property.nil?
          serialized_property = serialized_property.to_h
        end
        output_object[:properties] = serialized_property unless serialized_property.nil?

        output_object
      end

      def to_h
        self.validate
        hash = {}
        RouteTable.serialize_object(hash,self)
        hash
      end

      def self.ds_properties
        result = Array.new
        result.push :properties
        result
      end

      #
      # Deserializes given Ruby Hash into Model object.
      # @param object [Hash] Ruby Hash object to deserialize.
      # @return [RouteTable] Deserialized object.
      #
      def self.deserialize_object(output_object, object)
        return if object.nil?
        object.delete :name
        object.delete :type
        object.delete :api_version
        object.delete :location
        object.delete :tags
        object.delete :copy
        object.delete :comments
        conf = Configurator.new output_object.template
        conf.parent = output_object

        if object.key?(:properties)
          conf.properties object[:properties]
        end

        unless object.key?(:properties)
          conf.properties object
        end

        output_object
      end

      def get_name_template
        'rt'
      end

      def initialize(parent, init)
        super(parent, init)
        self.type = 'Microsoft.Network/routeTables' if self.type.nil?
        self.api_version = '2016-03-30' if self.api_version.nil?
        if init.is_a? Hash
          RouteTable.deserialize_object self, init.clone
        end 
      end

      # Configuration code
      class Configurator < Azure::ARM::ResourceConfigurator
        attr_accessor :parent
        attr_accessor :template
        # @param api_version
        #        A string, one of '2015-05-01-preview','2015-06-15','2016-03-30'
        def api_version(props)
          if props.is_a? String
            fail ArgumentError, "#{props} is an invalid value for @parent.api_version" unless ['2015-05-01-preview','2015-06-15','2016-03-30'].index(props)
            @parent.api_version = props
            return
          end
          @parent.api_version
        end
        # @param name
        #        String
        def name(props)
          if props.is_a? String or props.is_a? Azure::ARM::Expression
            @parent.name = props
            return
          end
          @parent.name
        end
        # @param properties
        #        RouteTablesProperties
        def properties(props)
          if @parent.properties.nil? and props.is_a? RouteTablesProperties
            @parent.properties = props
            @parent.properties.parent = @parent
            @parent.properties._rsrcpath = 'properties'
          end
          if @parent.properties.nil? and (props.is_a? Hash) and (Azure::ARM::TypeBase.matches_type props, RouteTablesProperties)
            @parent.properties = RouteTablesProperties.new(@parent, props)
            @parent.properties._rsrcpath = 'properties'
          end
          @parent.properties
        end
        # @param routes
        #        Array<Routes>
        #        Expression
        def routes(props)
          @parent.properties = (RouteTablesProperties.new @parent, nil) if @parent.properties.nil?
          if props.is_a? Array
            @parent.properties.routes = Array.new if @parent.properties.routes.nil?
            props.each { |p| @parent.properties.routes.push _routes_routes(p) }
            return @parent.properties.routes
          end
          _element = nil
          if _element.nil? and props.is_a? Routes
            _element = props
            _element.parent = @parent
            _element._rsrcpath = 'routes'
          end
          if _element.nil? and (props.is_a? Hash) and (Azure::ARM::TypeBase.matches_type props, Routes)
            _element = Routes.new(@parent, props)
            _element._rsrcpath = 'routes'
          end
          if _element.nil?
            _properties = nil
            if _properties.nil? and props.is_a? RouteProperties
              _properties = props
              _properties.parent = @parent
              _properties._rsrcpath = 'routes'
            end
            if _properties.nil? and (props.is_a? Hash) and (Azure::ARM::TypeBase.matches_type props, RouteProperties)
              _properties = RouteProperties.new(@parent, props)
              _properties._rsrcpath = 'routes'
            end
            unless _properties.nil?
              props[:properties] = _properties
              _element = Routes.new(@parent, props)
              _element._rsrcpath = 'routes'
              _element.properties = _properties
              _properties.parent = _element
            end
          end
          unless _element.nil?
            @parent.properties.routes = Array.new if @parent.properties.routes.nil?
            @parent.properties.routes.push _element
          end
          if @parent.properties.routes.nil? and props.is_a? Azure::ARM::Expression
            @parent.properties.routes = props
          end
          @parent.properties.routes
        end
        def _routes_routes(props)
          if props.is_a? Routes
            props.parent = @parent
            props._rsrcpath = 'routes'
            return props
          end
          if (props.is_a? Hash) and (Azure::ARM::TypeBase.matches_type props, Routes)
            _properties = Routes.new(@parent, props)
            _properties._rsrcpath = 'routes'
            return _properties
          end
          _properties = nil
          if _properties.nil? and props.is_a? RouteProperties
            _properties = props
            _properties.parent = @parent
            _properties._rsrcpath = 'routes'
          end
          if _properties.nil? and (props.is_a? Hash) and (Azure::ARM::TypeBase.matches_type props, RouteProperties)
            _properties = RouteProperties.new(@parent, props)
            _properties._rsrcpath = 'routes'
          end
          unless _properties.nil?
            props[:properties] = _properties
            routes = Routes.new(@parent, props)
            routes._rsrcpath = 'routes'
            routes.properties = _properties
            _properties.parent = routes
            return routes
          end
        end
        def initialize(template)
          @template = template
        end
        def create(init=nil,&block)
          @parent = RouteTable.new @template,init
          @template.resources.push @parent
          self.instance_exec(@parent,&block) if block
          @parent
        end
      end
      def configure(&block)
        conf = Configurator.new self.template
        conf.parent = self
        conf.instance_exec(self,&block) if block
        self
      end
    end
end
