# encoding: utf-8
# Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.

require_relative '../arm/module_definition'
require_relative './module_definition'

module Azure::ARM::Network
    #
    # Model object.
    #
    class RouteTablesProperties < Azure::ARM::TypeBase

      # @return Microsoft.Network/routeTables: Routes
      attr_writer :routes
      def routes(name=nil)
        if name and @routes and @routes.is_a? Array
          return @routes.find { | p | p.name == name } if name.is_a? String
          return @routes[name] if name.is_a? Integer
        end
        @routes
      end

      #
      # Validate the object. Throws ValidationError if validation fails.
      #
      def validate
      end

      #
      # Serializes given Model object into Ruby Hash.
      # @param object Model object to serialize.
      # @return [Hash] Serialized object in form of Ruby Hash.
      #
      def self.serialize_object(output_object, object)
        Azure::ARM::TypeBase.serialize_object(output_object, object)
        object.validate

        serialized_property = object.routes
        if serialized_property.is_a? Array
          unless serialized_property.nil?
            serializedarray = []
            serialized_property.each do |element|
              unless element.nil?
                element = element.to_h
              end
              serializedarray.push(element)
            end
            serialized_property = serializedarray
          end
        end
        if serialized_property.is_a? Azure::ARM::Expression
          unless serialized_property.nil?
            serialized_property = serialized_property.to_s
          end
        end
        output_object[:routes] = serialized_property unless serialized_property.nil?

        output_object
      end

      def to_h
        hash = {}
        RouteTablesProperties.serialize_object(hash,self)
        hash
      end

      def self.ds_properties
        result = Array.new 
        result.push :routes
        result
      end

      #
      # Deserializes given Ruby Hash into Model object.
      # @param object [Hash] Ruby Hash object to deserialize.
      # @return [RouteTablesProperties] Deserialized object.
      #
      def self.deserialize_object(output_object, object)
        return if object.nil?
        conf = Configurator.new
        conf.parent = output_object

        if object.key?(:routes)
          conf.routes object[:routes]
          object.delete :routes
        end

        output_object
      end

      def get_name_template
        'rtp'
        end

      def initialize(parent, init)
        super(parent)
        if init.is_a? Hash
          RouteTablesProperties.deserialize_object self, init.clone
        end
      end

      # Configuration code
      class Configurator < Azure::ARM::ResourceConfigurator
        attr_accessor :parent
        # @param routes
        #        Array<Routes>
        #        Expression
        def routes(props)
          if props.is_a? Array
            @parent.routes = Array.new if @parent.routes.nil?
            props.each { |p| @parent.routes.push _routes_routes(p) }
            return @parent.routes
          end
          _element = nil
          if _element.nil? and props.is_a? Routes
            _element = props
            _element.parent = @parent
            _element._rsrcpath = 'routes'
          end
          if _element.nil? and (props.is_a? Hash) and (Azure::ARM::TypeBase.matches_type props, Routes)
            _element = Routes.new(@parent, props)
            _element._rsrcpath = 'routes'
          end
          if _element.nil?
            _properties = nil
            if _properties.nil? and props.is_a? RouteProperties
              _properties = props
              _properties.parent = @parent
              _properties._rsrcpath = 'routes'
            end
            if _properties.nil? and (props.is_a? Hash) and (Azure::ARM::TypeBase.matches_type props, RouteProperties)
              _properties = RouteProperties.new(@parent, props)
              _properties._rsrcpath = 'routes'
            end
            unless _properties.nil?
              props[:properties] = _properties
              _element = Routes.new(@parent, props)
              _element._rsrcpath = 'routes'
              _element.properties = _properties
              _properties.parent = _element
            end
          end
          unless _element.nil?
            @parent.routes = Array.new if @parent.routes.nil?
            @parent.routes.push _element
          end
          if @parent.routes.nil? and props.is_a? Azure::ARM::Expression
            @parent.routes = props
          end
          @parent.routes
        end
        def _routes_routes(props)
          if props.is_a? Routes
            props.parent = @parent
            props._rsrcpath = 'routes'
            return props
          end
          if (props.is_a? Hash) and (Azure::ARM::TypeBase.matches_type props, Routes)
            _properties = Routes.new(@parent, props)
            _properties._rsrcpath = 'routes'
            return _properties
          end
          _properties = nil
          if _properties.nil? and props.is_a? RouteProperties
            _properties = props
            _properties.parent = @parent
            _properties._rsrcpath = 'routes'
          end
          if _properties.nil? and (props.is_a? Hash) and (Azure::ARM::TypeBase.matches_type props, RouteProperties)
            _properties = RouteProperties.new(@parent, props)
            _properties._rsrcpath = 'routes'
          end
          unless _properties.nil?
            props[:properties] = _properties
            routes = Routes.new(@parent, props)
            routes._rsrcpath = 'routes'
            routes.properties = _properties
            _properties.parent = routes
            return routes
          end
        end
        def create(init=nil,&block)
          @parent = RouteTablesProperties.new nil, init
          self.instance_exec(@parent,&block) if block
          @parent
        end
      end
      def configure(&block)
        conf = Configurator.new
        conf.parent = self
        conf.instance_exec(self,&block) if block
        self
      end
    end
end
