# encoding: utf-8
# Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.

require_relative '../arm/module_definition'
require_relative './module_definition'

module Azure::ARM::Network
    #
    # Model object.
    #
    class Subnet < Azure::ARM::TypeBase

      # @return [String]
      attr_accessor :name

      # @return [SubnetProperties]
      attr_accessor :properties

      #
      # Validate the object. Throws ValidationError if validation fails.
      #
      def validate
        fail ArgumentError, 'property name is nil' if @name.nil?
        fail ArgumentError, 'property properties is nil' if @properties.nil?
        @properties.validate unless @properties.nil?
      end

      #
      # Serializes given Model object into Ruby Hash.
      # @param object Model object to serialize.
      # @return [Hash] Serialized object in form of Ruby Hash.
      #
      def self.serialize_object(output_object, object)
        Azure::ARM::TypeBase.serialize_object(output_object, object)
        object.validate

        serialized_property = object.name
        output_object[:name] = serialized_property unless serialized_property.nil?

        serialized_property = object.properties
        unless serialized_property.nil?
          serialized_property = serialized_property.to_h
        end
        output_object[:properties] = serialized_property unless serialized_property.nil?

        output_object
      end

      def to_h
        hash = {}
        Subnet.serialize_object(hash,self)
        hash
      end

      def self.ds_properties
        result = Array.new 
        result.push :properties
        result
      end

      #
      # Deserializes given Ruby Hash into Model object.
      # @param object [Hash] Ruby Hash object to deserialize.
      # @return [Subnet] Deserialized object.
      #
      def self.deserialize_object(output_object, object)
        return if object.nil?
        conf = Configurator.new
        conf.parent = output_object

        if object.key?(:name)
          conf.name object[:name]
          object.delete :name
        end

        if object.key?(:properties)
          conf.properties object[:properties]
        end

                unless object.key?(:properties)
          conf.properties object
        end

        output_object
      end

      def get_name_template
        's'
        end

      def initialize(parent, init)
        super(parent)
        if init.is_a? Hash
          Subnet.deserialize_object self, init.clone
        end
      end

      # Configuration code
      class Configurator < Azure::ARM::ResourceConfigurator
        attr_accessor :parent
        # @param name
        #        String
        def name(props)
          if props.is_a? String or props.is_a? Azure::ARM::Expression
            @parent.name = props
            return
          end
          @parent.name
        end
        # @param properties
        #        SubnetProperties
        def properties(props)
          if @parent.properties.nil? and props.is_a? SubnetProperties
            @parent.properties = props
            @parent.properties.parent = @parent
            @parent.properties._rsrcpath = 'properties'
          end
          if @parent.properties.nil? and (props.is_a? Hash) and (Azure::ARM::TypeBase.matches_type props, SubnetProperties)
            @parent.properties = SubnetProperties.new(@parent, props)
            @parent.properties._rsrcpath = 'properties'
          end
          @parent.properties
        end
        # @param address_prefix
        #        String
        def address_prefix(props)
          @parent.properties = (SubnetProperties.new @parent, nil) if @parent.properties.nil?
          if props.is_a? String or props.is_a? Azure::ARM::Expression
            @parent.properties.address_prefix = props
            return
          end
          @parent.properties.address_prefix
        end
        # @param network_security_group
        #        Id
        def network_security_group(props)
          @parent.properties = (SubnetProperties.new @parent, nil) if @parent.properties.nil?
          if @parent.properties.network_security_group.nil? and props.is_a? Id
            @parent.properties.network_security_group = props
            @parent.properties.network_security_group.parent = @parent
            @parent.properties.network_security_group._rsrcpath = 'networkSecurityGroup'
          end
          if @parent.properties.network_security_group.nil? and (props.is_a? Hash) and (Azure::ARM::TypeBase.matches_type props, Id)
            @parent.properties.network_security_group = Id.new(@parent, props)
            @parent.properties.network_security_group._rsrcpath = 'networkSecurityGroup'
          end
          if @parent.properties.network_security_group.nil? and (props.respond_to? :to_rsrcid)
            @parent.properties.network_security_group = Id.new(@parent, id: props.to_rsrcid.to_s)
            if props.is_a? Azure::ARM::TypeBase and !props.containing_resource.nil?
              @parent.containing_resource.add_dependency props.containing_resource
            end
          end
          @parent.properties.network_security_group
        end
        # @param route_table
        #        Id
        def route_table(props)
          @parent.properties = (SubnetProperties.new @parent, nil) if @parent.properties.nil?
          if @parent.properties.route_table.nil? and props.is_a? Id
            @parent.properties.route_table = props
            @parent.properties.route_table.parent = @parent
            @parent.properties.route_table._rsrcpath = 'routeTable'
          end
          if @parent.properties.route_table.nil? and (props.is_a? Hash) and (Azure::ARM::TypeBase.matches_type props, Id)
            @parent.properties.route_table = Id.new(@parent, props)
            @parent.properties.route_table._rsrcpath = 'routeTable'
          end
          if @parent.properties.route_table.nil? and (props.respond_to? :to_rsrcid)
            @parent.properties.route_table = Id.new(@parent, id: props.to_rsrcid.to_s)
            if props.is_a? Azure::ARM::TypeBase and !props.containing_resource.nil?
              @parent.containing_resource.add_dependency props.containing_resource
            end
          end
          @parent.properties.route_table
        end
        def create(init=nil,&block)
          @parent = Subnet.new nil, init
          self.instance_exec(@parent,&block) if block
          @parent
        end
      end
      def configure(&block)
        conf = Configurator.new
        conf.parent = self
        conf.instance_exec(self,&block) if block
        self
      end
    end
end
