# encoding: utf-8
# Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.

require_relative '../arm/module_definition'
require_relative './module_definition'

module Azure::ARM::Compute
    #
    # Model object.
    #
    class AvailabilitySetsProperties < Azure::ARM::TypeBase

      # @return Microsoft.Compute/availabilitySets - Platform update domain
      # count
      attr_accessor :platform_update_domain_count

      # @return Microsoft.Compute/availabilitySets - Platform fault domain
      # count
      attr_accessor :platform_fault_domain_count

      #
      # Validate the object. Throws ValidationError if validation fails.
      #
      def validate
      end

      #
      # Serializes given Model object into Ruby Hash.
      # @param object Model object to serialize.
      # @return [Hash] Serialized object in form of Ruby Hash.
      #
      def self.serialize_object(output_object, object)
        Azure::ARM::TypeBase.serialize_object(output_object, object)
        object.validate

        serialized_property = object.platform_update_domain_count
        if serialized_property.is_a? Azure::ARM::Expression
          unless serialized_property.nil?
            serialized_property = serialized_property.to_s
          end
        end
        output_object[:platformUpdateDomainCount] = serialized_property unless serialized_property.nil?

        serialized_property = object.platform_fault_domain_count
        if serialized_property.is_a? Azure::ARM::Expression
          unless serialized_property.nil?
            serialized_property = serialized_property.to_s
          end
        end
        output_object[:platformFaultDomainCount] = serialized_property unless serialized_property.nil?

        output_object
      end

      def to_h
        hash = {}
        AvailabilitySetsProperties.serialize_object(hash,self)
        hash
      end

      def self.ds_properties
        result = Array.new 
        result.push :platform_update_domain_count
        result.push :platform_fault_domain_count
        result
      end

      #
      # Deserializes given Ruby Hash into Model object.
      # @param object [Hash] Ruby Hash object to deserialize.
      # @return [AvailabilitySetsProperties] Deserialized object.
      #
      def self.deserialize_object(output_object, object)
        return if object.nil?
        conf = Configurator.new
        conf.parent = output_object

        if object.key?(:platform_update_domain_count)
          conf.platform_update_domain_count object[:platform_update_domain_count]
          object.delete :platform_update_domain_count
        end

        if object.key?(:platform_fault_domain_count)
          conf.platform_fault_domain_count object[:platform_fault_domain_count]
          object.delete :platform_fault_domain_count
        end

        output_object
      end

      def get_name_template
        'asp'
        end

      def initialize(parent, init)
        super(parent)
        if init.is_a? Hash
          AvailabilitySetsProperties.deserialize_object self, init.clone
        end
      end

      # Configuration code
      class Configurator < Azure::ARM::ResourceConfigurator
        attr_accessor :parent
        # @param platform_update_domain_count
        #        Fixnum
        #        Expression
        def platform_update_domain_count(props)
          if props.is_a? Fixnum or props.is_a? Azure::ARM::Expression
            @parent.platform_update_domain_count = props
            return
          end
          if @parent.platform_update_domain_count.nil? and props.is_a? Azure::ARM::Expression
            @parent.platform_update_domain_count = props
          end
          @parent.platform_update_domain_count
        end
        # @param platform_fault_domain_count
        #        Fixnum
        #        Expression
        def platform_fault_domain_count(props)
          if props.is_a? Fixnum or props.is_a? Azure::ARM::Expression
            @parent.platform_fault_domain_count = props
            return
          end
          if @parent.platform_fault_domain_count.nil? and props.is_a? Azure::ARM::Expression
            @parent.platform_fault_domain_count = props
          end
          @parent.platform_fault_domain_count
        end
        def create(init=nil,&block)
          @parent = AvailabilitySetsProperties.new nil, init
          self.instance_exec(@parent,&block) if block
          @parent
        end
      end
      def configure(&block)
        conf = Configurator.new
        conf.parent = self
        conf.instance_exec(self,&block) if block
        self
      end
    end
end
