# encoding: utf-8
# Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.

require_relative '../arm/module_definition'
require_relative './module_definition'

module Azure::ARM::Compute
    #
    # Model object.
    #
    class PublicKey < Azure::ARM::TypeBase

      # @return [String]
      attr_accessor :path

      # @return [String]
      attr_accessor :key_data

      #
      # Validate the object. Throws ValidationError if validation fails.
      #
      def validate
        # Nothing to validate
      end

      #
      # Serializes given Model object into Ruby Hash.
      # @param object Model object to serialize.
      # @return [Hash] Serialized object in form of Ruby Hash.
      #
      def self.serialize_object(output_object, object)
        Azure::ARM::TypeBase.serialize_object(output_object, object)
        object.validate

        serialized_property = object.path
        output_object[:path] = serialized_property unless serialized_property.nil?

        serialized_property = object.key_data
        output_object[:keyData] = serialized_property unless serialized_property.nil?

        output_object
      end

      def to_h
        hash = {}
        PublicKey.serialize_object(hash,self)
        hash
      end

      def self.ds_properties
        result = Array.new 
        result.push :path
        result.push :key_data
        result
      end

      #
      # Deserializes given Ruby Hash into Model object.
      # @param object [Hash] Ruby Hash object to deserialize.
      # @return [PublicKey] Deserialized object.
      #
      def self.deserialize_object(output_object, object)
        return if object.nil?
        conf = Configurator.new
        conf.parent = output_object

        if object.key?(:path)
          conf.path object[:path]
          object.delete :path
        end

        if object.key?(:key_data)
          conf.key_data object[:key_data]
          object.delete :key_data
        end

        output_object
      end

      def get_name_template
        'pk'
        end

      def initialize(parent, init)
        super(parent)
        if init.is_a? Hash
          PublicKey.deserialize_object self, init.clone
        end
      end

      # Configuration code
      class Configurator < Azure::ARM::ResourceConfigurator
        attr_accessor :parent
        # @param path
        #        String
        def path(props)
          if props.is_a? String or props.is_a? Azure::ARM::Expression
            @parent.path = props
            return
          end
          @parent.path
        end
        # @param key_data
        #        String
        def key_data(props)
          if props.is_a? String or props.is_a? Azure::ARM::Expression
            @parent.key_data = props
            return
          end
          @parent.key_data
        end
        def create(init=nil,&block)
          @parent = PublicKey.new nil, init
          self.instance_exec(@parent,&block) if block
          @parent
        end
      end
      def configure(&block)
        conf = Configurator.new
        conf.parent = self
        conf.instance_exec(self,&block) if block
        self
      end
    end
end
