# encoding: utf-8
# Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.

require_relative '../arm/module_definition'
require_relative './module_definition'

module Azure::ARM::Compute
    #
    # Model object.
    #
    class Vhd < Azure::ARM::TypeBase

      # @return [String]
      attr_accessor :uri

      #
      # Validate the object. Throws ValidationError if validation fails.
      #
      def validate
        fail ArgumentError, 'property uri is nil' if @uri.nil?
      end

      #
      # Serializes given Model object into Ruby Hash.
      # @param object Model object to serialize.
      # @return [Hash] Serialized object in form of Ruby Hash.
      #
      def self.serialize_object(output_object, object)
        Azure::ARM::TypeBase.serialize_object(output_object, object)
        object.validate

        serialized_property = object.uri
        output_object[:uri] = serialized_property unless serialized_property.nil?

        output_object
      end

      def to_h
        hash = {}
        Vhd.serialize_object(hash,self)
        hash
      end

      def self.ds_properties
        result = Array.new 
        result.push :uri
        result
      end

      #
      # Deserializes given Ruby Hash into Model object.
      # @param object [Hash] Ruby Hash object to deserialize.
      # @return [Vhd] Deserialized object.
      #
      def self.deserialize_object(output_object, object)
        return if object.nil?
        conf = Configurator.new
        conf.parent = output_object

        if object.key?(:uri)
          conf.uri object[:uri]
          object.delete :uri
        end

        output_object
      end

      def get_name_template
        'v'
        end

      def initialize(parent, init)
        super(parent)
        if init.is_a? Hash
          Vhd.deserialize_object self, init.clone
        end
      end

      # Configuration code
      class Configurator < Azure::ARM::ResourceConfigurator
        attr_accessor :parent
        # @param uri
        #        String
        def uri(props)
          if props.is_a? String or props.is_a? Azure::ARM::Expression
            @parent.uri = props
            return
          end
          @parent.uri
        end
        def create(init=nil,&block)
          @parent = Vhd.new nil, init
          self.instance_exec(@parent,&block) if block
          @parent
        end
      end
      def configure(&block)
        conf = Configurator.new
        conf.parent = self
        conf.instance_exec(self,&block) if block
        self
      end
    end
end
