# encoding: utf-8
# Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.

require_relative '../arm/module_definition'
require_relative './module_definition'

module Azure::ARM::Compute
    #
    # Microsoft.Compute/virtualMachineScaleSets
    #
    class VirtualMachineScaleSet < Azure::ARM::ResourceBase

      # @return [Sku]
      attr_accessor :sku

      # @return [VirtualMachineScaleSetsProperties]
      attr_accessor :properties

      #
      # Validate the object. Throws ValidationError if validation fails.
      #
      def validate
        fail ArgumentError, 'property type is nil' if self.type.nil?
        fail ArgumentError, 'property api_version is nil' if self.api_version.nil?
        fail ArgumentError, 'property sku is nil' if self.sku.nil?
        fail ArgumentError, 'property properties is nil' if self.properties.nil?
        @sku.validate unless @sku.nil?
        @properties.validate unless @properties.nil?
      end

      #
      # Serializes given Model object into Ruby Hash.
      # @param object Model object to serialize.
      # @return [Hash] Serialized object in form of Ruby Hash.
      #
      def self.serialize_object(output_object, object)
        Azure::ARM::ResourceBase.serialize_object(output_object, object)
        object.validate

        serialized_property = object.sku
        unless serialized_property.nil?
          serialized_property = serialized_property.to_h
        end
        output_object[:sku] = serialized_property unless serialized_property.nil?

        serialized_property = object.properties
        unless serialized_property.nil?
          serialized_property = serialized_property.to_h
        end
        output_object[:properties] = serialized_property unless serialized_property.nil?

        output_object
      end

      def to_h
        self.validate
        hash = {}
        VirtualMachineScaleSet.serialize_object(hash,self)
        hash
      end

      def self.ds_properties
        result = Array.new
        result.push :sku
        result.push :properties
        result
      end

      #
      # Deserializes given Ruby Hash into Model object.
      # @param object [Hash] Ruby Hash object to deserialize.
      # @return [VirtualMachineScaleSet] Deserialized object.
      #
      def self.deserialize_object(output_object, object)
        return if object.nil?
        object.delete :name
        object.delete :type
        object.delete :api_version
        object.delete :location
        object.delete :tags
        object.delete :copy
        object.delete :comments
        conf = Configurator.new output_object.template
        conf.parent = output_object

        if object.key?(:sku)
          conf.sku object[:sku]
          object.delete :sku
        end

        if object.key?(:properties)
          conf.properties object[:properties]
        end

        unless object.key?(:properties)
          conf.properties object
        end

        output_object
      end

      def get_name_template
        'vmss'
      end

      def initialize(parent, init)
        super(parent, init)
        self.type = 'Microsoft.Compute/virtualMachineScaleSets' if self.type.nil?
        self.api_version = '2015-06-15' if self.api_version.nil?
        if init.is_a? Hash
          VirtualMachineScaleSet.deserialize_object self, init.clone
        end 
      end

      # Configuration code
      class Configurator < Azure::ARM::ResourceConfigurator
        attr_accessor :parent
        attr_accessor :template
        # @param api_version
        #        A string, one of '2015-05-01-preview','2015-06-15'
        def api_version(props)
          if props.is_a? String
            fail ArgumentError, "#{props} is an invalid value for @parent.api_version" unless ['2015-05-01-preview','2015-06-15'].index(props)
            @parent.api_version = props
            return
          end
          @parent.api_version
        end
        # @param sku
        #        Sku
        def sku(props)
          if @parent.sku.nil? and props.is_a? Sku
            @parent.sku = props
            @parent.sku.parent = @parent
            @parent.sku._rsrcpath = 'sku'
          end
          if @parent.sku.nil? and (props.is_a? Hash) and (Azure::ARM::TypeBase.matches_type props, Sku)
            @parent.sku = Sku.new(@parent, props)
            @parent.sku._rsrcpath = 'sku'
          end
          @parent.sku
        end
        # @param properties
        #        VirtualMachineScaleSetsProperties
        def properties(props)
          if @parent.properties.nil? and props.is_a? VirtualMachineScaleSetsProperties
            @parent.properties = props
            @parent.properties.parent = @parent
            @parent.properties._rsrcpath = 'properties'
          end
          if @parent.properties.nil? and (props.is_a? Hash) and (Azure::ARM::TypeBase.matches_type props, VirtualMachineScaleSetsProperties)
            @parent.properties = VirtualMachineScaleSetsProperties.new(@parent, props)
            @parent.properties._rsrcpath = 'properties'
          end
          @parent.properties
        end
        # @param upgrade_policy
        #        UpgradePolicy
        #        Expression
        def upgrade_policy(props)
          @parent.properties = (VirtualMachineScaleSetsProperties.new @parent, nil) if @parent.properties.nil?
          if @parent.properties.upgrade_policy.nil? and props.is_a? UpgradePolicy
            @parent.properties.upgrade_policy = props
            @parent.properties.upgrade_policy.parent = @parent
            @parent.properties.upgrade_policy._rsrcpath = 'upgradePolicy'
          end
          if @parent.properties.upgrade_policy.nil? and (props.is_a? Hash) and (Azure::ARM::TypeBase.matches_type props, UpgradePolicy)
            @parent.properties.upgrade_policy = UpgradePolicy.new(@parent, props)
            @parent.properties.upgrade_policy._rsrcpath = 'upgradePolicy'
          end
          if @parent.properties.upgrade_policy.nil? and props.is_a? Azure::ARM::Expression
            @parent.properties.upgrade_policy = props
          end
          @parent.properties.upgrade_policy
        end
        # @param virtual_machine_profile
        #        VirtualMachineProfile
        #        Expression
        def virtual_machine_profile(props)
          @parent.properties = (VirtualMachineScaleSetsProperties.new @parent, nil) if @parent.properties.nil?
          if @parent.properties.virtual_machine_profile.nil? and props.is_a? VirtualMachineProfile
            @parent.properties.virtual_machine_profile = props
            @parent.properties.virtual_machine_profile.parent = @parent
            @parent.properties.virtual_machine_profile._rsrcpath = 'virtualMachineProfile'
          end
          if @parent.properties.virtual_machine_profile.nil? and (props.is_a? Hash) and (Azure::ARM::TypeBase.matches_type props, VirtualMachineProfile)
            @parent.properties.virtual_machine_profile = VirtualMachineProfile.new(@parent, props)
            @parent.properties.virtual_machine_profile._rsrcpath = 'virtualMachineProfile'
          end
          if @parent.properties.virtual_machine_profile.nil? and props.is_a? Azure::ARM::Expression
            @parent.properties.virtual_machine_profile = props
          end
          @parent.properties.virtual_machine_profile
        end
        def initialize(template)
          @template = template
        end
        def create(init=nil,&block)
          @parent = VirtualMachineScaleSet.new @template,init
          @template.resources.push @parent
          self.instance_exec(@parent,&block) if block
          @parent
        end
      end
      def configure(&block)
        conf = Configurator.new self.template
        conf.parent = self
        conf.instance_exec(self,&block) if block
        self
      end
    end
end
