# encoding: utf-8
# Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.

require_relative '../arm/module_definition'
require_relative './module_definition'

module Azure::ARM::Compute
    #
    # Model object.
    #
    class VirtualMachineScaleSetExtensionProfile < Azure::ARM::TypeBase

      # @return [Array<VirtualMachineScaleSetExtension>]
      attr_writer :extensions
      def extensions(name=nil)
        if name and @extensions and @extensions.is_a? Array
          return @extensions.find { | p | p.name == name } if name.is_a? String
          return @extensions[name] if name.is_a? Integer
        end
        @extensions
      end

      #
      # Validate the object. Throws ValidationError if validation fails.
      #
      def validate
        @extensions.each{ |e| e.validate if e.respond_to?(:validate) } unless @extensions.nil?
      end

      #
      # Serializes given Model object into Ruby Hash.
      # @param object Model object to serialize.
      # @return [Hash] Serialized object in form of Ruby Hash.
      #
      def self.serialize_object(output_object, object)
        Azure::ARM::TypeBase.serialize_object(output_object, object)
        object.validate

        serialized_property = object.extensions
        unless serialized_property.nil?
          serializedarray = []
          serialized_property.each do |element|
            unless element.nil?
              element = element.to_h
            end
            serializedarray.push(element)
          end
          serialized_property = serializedarray
        end
        output_object[:extensions] = serialized_property unless serialized_property.nil?

        output_object
      end

      def to_h
        hash = {}
        VirtualMachineScaleSetExtensionProfile.serialize_object(hash,self)
        hash
      end

      def self.ds_properties
        result = Array.new 
        result.push :extensions
        result
      end

      #
      # Deserializes given Ruby Hash into Model object.
      # @param object [Hash] Ruby Hash object to deserialize.
      # @return [VirtualMachineScaleSetExtensionProfile] Deserialized object.
      #
      def self.deserialize_object(output_object, object)
        return if object.nil?
        conf = Configurator.new
        conf.parent = output_object

        if object.key?(:extensions)
          conf.extensions object[:extensions]
          object.delete :extensions
        end

        output_object
      end

      def get_name_template
        'vmssep'
        end

      def initialize(parent, init)
        super(parent)
        if init.is_a? Hash
          VirtualMachineScaleSetExtensionProfile.deserialize_object self, init.clone
        end
      end

      # Configuration code
      class Configurator < Azure::ARM::ResourceConfigurator
        attr_accessor :parent
        # @param extensions
        #        Array<VirtualMachineScaleSetExtension>
        def extensions(props)
          if props.is_a? Array
            @parent.extensions = Array.new if @parent.extensions.nil?
            props.each { |p| @parent.extensions.push _extensions_virtualmachinescalesetextension(p) }
            return @parent.extensions
          end
          _element = nil
          if _element.nil? and props.is_a? VirtualMachineScaleSetExtension
            _element = props
            _element.parent = @parent
            _element._rsrcpath = 'extensions'
          end
          if _element.nil? and (props.is_a? Hash) and (Azure::ARM::TypeBase.matches_type props, VirtualMachineScaleSetExtension)
            _element = VirtualMachineScaleSetExtension.new(@parent, props)
            _element._rsrcpath = 'extensions'
          end
          if _element.nil?
            _properties = nil
            if _properties.nil? and props.is_a? VirtualMachineScaleSetExtensionProperties
              _properties = props
              _properties.parent = @parent
              _properties._rsrcpath = 'extensions'
            end
            if _properties.nil? and (props.is_a? Hash) and (Azure::ARM::TypeBase.matches_type props, VirtualMachineScaleSetExtensionProperties)
              _properties = VirtualMachineScaleSetExtensionProperties.new(@parent, props)
              _properties._rsrcpath = 'extensions'
            end
            unless _properties.nil?
              props[:properties] = _properties
              _element = VirtualMachineScaleSetExtension.new(@parent, props)
              _element._rsrcpath = 'extensions'
              _element.properties = _properties
              _properties.parent = _element
            end
          end
          unless _element.nil?
            @parent.extensions = Array.new if @parent.extensions.nil?
            @parent.extensions.push _element
          end
          @parent.extensions
        end
        def _extensions_virtualmachinescalesetextension(props)
          if props.is_a? VirtualMachineScaleSetExtension
            props.parent = @parent
            props._rsrcpath = 'extensions'
            return props
          end
          if (props.is_a? Hash) and (Azure::ARM::TypeBase.matches_type props, VirtualMachineScaleSetExtension)
            _properties = VirtualMachineScaleSetExtension.new(@parent, props)
            _properties._rsrcpath = 'extensions'
            return _properties
          end
          _properties = nil
          if _properties.nil? and props.is_a? VirtualMachineScaleSetExtensionProperties
            _properties = props
            _properties.parent = @parent
            _properties._rsrcpath = 'extensions'
          end
          if _properties.nil? and (props.is_a? Hash) and (Azure::ARM::TypeBase.matches_type props, VirtualMachineScaleSetExtensionProperties)
            _properties = VirtualMachineScaleSetExtensionProperties.new(@parent, props)
            _properties._rsrcpath = 'extensions'
          end
          unless _properties.nil?
            props[:properties] = _properties
            extensions = VirtualMachineScaleSetExtension.new(@parent, props)
            extensions._rsrcpath = 'extensions'
            extensions.properties = _properties
            _properties.parent = extensions
            return extensions
          end
        end
        def create(init=nil,&block)
          @parent = VirtualMachineScaleSetExtensionProfile.new nil, init
          self.instance_exec(@parent,&block) if block
          @parent
        end
      end
      def configure(&block)
        conf = Configurator.new
        conf.parent = self
        conf.instance_exec(self,&block) if block
        self
      end
    end
end
