# encoding: utf-8
# Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.

require_relative '../arm/module_definition'
require_relative './module_definition'

module Azure::ARM::Compute
    #
    # Model object.
    #
    class WinRMListener < Azure::ARM::TypeBase

      # @return
      attr_accessor :protocol

      # @return [String]
      attr_accessor :certificate_url

      #
      # Validate the object. Throws ValidationError if validation fails.
      #
      def validate
        fail ArgumentError, 'property protocol is nil' if @protocol.nil?
        fail ArgumentError, 'property certificate_url is nil' if @certificate_url.nil?
      end

      #
      # Serializes given Model object into Ruby Hash.
      # @param object Model object to serialize.
      # @return [Hash] Serialized object in form of Ruby Hash.
      #
      def self.serialize_object(output_object, object)
        Azure::ARM::TypeBase.serialize_object(output_object, object)
        object.validate

        serialized_property = object.protocol
        if serialized_property.is_a? Azure::ARM::Expression
          unless serialized_property.nil?
            serialized_property = serialized_property.to_s
          end
        end
        output_object[:protocol] = serialized_property unless serialized_property.nil?

        serialized_property = object.certificate_url
        output_object[:certificateUrl] = serialized_property unless serialized_property.nil?

        output_object
      end

      def to_h
        hash = {}
        WinRMListener.serialize_object(hash,self)
        hash
      end

      def self.ds_properties
        result = Array.new 
        result.push :protocol
        result.push :certificate_url
        result
      end

      #
      # Deserializes given Ruby Hash into Model object.
      # @param object [Hash] Ruby Hash object to deserialize.
      # @return [WinRMListener] Deserialized object.
      #
      def self.deserialize_object(output_object, object)
        return if object.nil?
        conf = Configurator.new
        conf.parent = output_object

        if object.key?(:protocol)
          conf.protocol object[:protocol]
          object.delete :protocol
        end

        if object.key?(:certificate_url)
          conf.certificate_url object[:certificate_url]
          object.delete :certificate_url
        end

        output_object
      end

      def get_name_template
        'wrml'
        end

      def initialize(parent, init)
        super(parent)
        if init.is_a? Hash
          WinRMListener.deserialize_object self, init.clone
        end
      end

      # Configuration code
      class Configurator < Azure::ARM::ResourceConfigurator
        attr_accessor :parent
        # @param protocol
        #        A string, one of 'Http','Https'
        #        Expression
        def protocol(props)
          if props.is_a? String
            fail ArgumentError, "#{props} is an invalid value for @parent.protocol" unless ['Http','Https'].index(props)
            @parent.protocol = props
            return
          end
          if @parent.protocol.nil? and props.is_a? Azure::ARM::Expression
            @parent.protocol = props
          end
          @parent.protocol
        end
        # @param certificate_url
        #        String
        def certificate_url(props)
          if props.is_a? String or props.is_a? Azure::ARM::Expression
            @parent.certificate_url = props
            return
          end
          @parent.certificate_url
        end
        def create(init=nil,&block)
          @parent = WinRMListener.new nil, init
          self.instance_exec(@parent,&block) if block
          @parent
        end
      end
      def configure(&block)
        conf = Configurator.new
        conf.parent = self
        conf.instance_exec(self,&block) if block
        self
      end
    end
end
