# encoding: utf-8
# Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.

require_relative '../arm/module_definition'
require_relative './module_definition'

module Azure::ARM::Compute
    #
    # Model object.
    #
    class WinRM < Azure::ARM::TypeBase

      # @return [Array<WinRMListener>]
      attr_writer :listeners
      def listeners(name=nil)
        if name and @listeners and @listeners.is_a? Array
          return @listeners.find { | p | p.name == name } if name.is_a? String
          return @listeners[name] if name.is_a? Integer
        end
        @listeners
      end

      #
      # Validate the object. Throws ValidationError if validation fails.
      #
      def validate
        fail ArgumentError, 'property listeners is nil' if @listeners.nil?
        @listeners.each{ |e| e.validate if e.respond_to?(:validate) } unless @listeners.nil?
      end

      #
      # Serializes given Model object into Ruby Hash.
      # @param object Model object to serialize.
      # @return [Hash] Serialized object in form of Ruby Hash.
      #
      def self.serialize_object(output_object, object)
        Azure::ARM::TypeBase.serialize_object(output_object, object)
        object.validate

        serialized_property = object.listeners
        unless serialized_property.nil?
          serializedarray = []
          serialized_property.each do |element|
            unless element.nil?
              element = element.to_h
            end
            serializedarray.push(element)
          end
          serialized_property = serializedarray
        end
        output_object[:listeners] = serialized_property unless serialized_property.nil?

        output_object
      end

      def to_h
        hash = {}
        WinRM.serialize_object(hash,self)
        hash
      end

      def self.ds_properties
        result = Array.new 
        result.push :listeners
        result
      end

      #
      # Deserializes given Ruby Hash into Model object.
      # @param object [Hash] Ruby Hash object to deserialize.
      # @return [WinRM] Deserialized object.
      #
      def self.deserialize_object(output_object, object)
        return if object.nil?
        conf = Configurator.new
        conf.parent = output_object

        if object.key?(:listeners)
          conf.listeners object[:listeners]
          object.delete :listeners
        end

        output_object
      end

      def get_name_template
        'wrm'
        end

      def initialize(parent, init)
        super(parent)
        if init.is_a? Hash
          WinRM.deserialize_object self, init.clone
        end
      end

      # Configuration code
      class Configurator < Azure::ARM::ResourceConfigurator
        attr_accessor :parent
        # @param listeners
        #        Array<WinRMListener>
        def listeners(props)
          if props.is_a? Array
            @parent.listeners = Array.new if @parent.listeners.nil?
            props.each { |p| @parent.listeners.push _listeners_winrmlistener(p) }
            return @parent.listeners
          end
          _element = nil
          if _element.nil? and props.is_a? WinRMListener
            _element = props
            _element.parent = @parent
            _element._rsrcpath = 'listeners'
          end
          if _element.nil? and (props.is_a? Hash) and (Azure::ARM::TypeBase.matches_type props, WinRMListener)
            _element = WinRMListener.new(@parent, props)
            _element._rsrcpath = 'listeners'
          end
          unless _element.nil?
            @parent.listeners = Array.new if @parent.listeners.nil?
            @parent.listeners.push _element
          end
          @parent.listeners
        end
        def _listeners_winrmlistener(props)
          if props.is_a? WinRMListener
            props.parent = @parent
            props._rsrcpath = 'listeners'
            return props
          end
          if (props.is_a? Hash) and (Azure::ARM::TypeBase.matches_type props, WinRMListener)
            _properties = WinRMListener.new(@parent, props)
            _properties._rsrcpath = 'listeners'
            return _properties
          end
        end
        def create(init=nil,&block)
          @parent = WinRM.new nil, init
          self.instance_exec(@parent,&block) if block
          @parent
        end
      end
      def configure(&block)
        conf = Configurator.new
        conf.parent = self
        conf.instance_exec(self,&block) if block
        self
      end
    end
end
