
module Azure::ARM::Locations

  AustraliaEast = 'Australia East'
  AustraliaSoutheast = 'Australia Southeast'
  BrazilSouth = 'Brazil South'
  CanadaCentral = 'Canada Central'
  CanadaEast = 'Canada East'
  CentralIndia = 'Central India'
  CentralUs = 'Central US'
  ChinaEast = 'China East'
  ChinaNorth = 'China North'
  EastAsia = 'East Asia'
  EastUS = 'East US'
  EastUS2 = 'East US 2'
  GermanyCentral = 'Germany Central'
  GermanyNortheast = 'Germany Northeast'
  JapanEast = 'Japan East'
  JapanWest = 'Japan West'
  NorthCentralUS = 'North Central US'
  NorthEurope = 'North Europe'
  SouthCentralUS = 'South Central US'
  SoutheastAsia = 'Southeast Asia'
  SouthIndia = 'South India'
  UnitedKingdom = 'United Kingdom'
  WestEurope = 'West Europe'
  WestIndia = 'West India'
  WestUS = 'West US'

end