# encoding: utf-8
# Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.

require_relative 'armresource_base'

module Azure::ARM

    #
    # Model object.
    #
    class ResourceBase < ARMResourceBase

      include Azure::ARM::PredefinedExpressions

      # @return Location to deploy resource to
      attr_accessor :location

      # @return Name-value pairs to add to the resource
      attr_accessor :tags

      # @return [ResourceCopy]
      attr_accessor :copy

      # @return [String]
      attr_accessor :comments

      #
      # Validate the object. Throws ArgumentError if validation fails.
      #
      def self.validate(object)
        object.copy.validate unless object.copy.nil?
      end

      #
      # Serializes given Model object into Ruby Hash.
      # @param object Model object to serialize.
      # @return [Hash] Serialized object in form of Ruby Hash.
      #
      def self.serialize_object(output_object, object)
        object.validate

        ARMResourceBase.serialize_object(output_object, object)

        serialized_property = object.location
        output_object[:location] = serialized_property unless serialized_property.nil?

        serialized_property = object.tags
        output_object[:tags] = serialized_property unless serialized_property.nil?

        serialized_property = object.copy
        unless serialized_property.nil?
          serialized_property = serialized_property.to_h
        end
        output_object[:copy] = serialized_property unless serialized_property.nil?

        serialized_property = object.comments
        output_object[:comments] = serialized_property unless serialized_property.nil?

        output_object
      end

      def to_h
        hash = {}
        ResourceBase.serialize_object(hash, self)
        hash
      end

      def initialize(parent, init)
        super(parent, init)
        @location = '[resourceGroup().location]'
        if init.is_a? Hash
          @location = init[:location] if init.key? :location
          @tags = init[:tags]
          @copy = init[:copy]
          @comments = init[:comments]
        end
      end
    end

end
