# encoding: utf-8
# Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.

require_relative '../arm/module_definition'
require_relative './module_definition'

module Azure::ARM::Web
    #
    # Model object.
    #
    class ServerfarmsProperties < Azure::ARM::TypeBase

      # @return [String] Microsoft.Web/serverfarms: Name of the server farm.
      attr_accessor :name

      # @return Microsoft.Web/serverfarms: The instance count, which is the
      # number of virtual machines dedicated to the farm. Supported values
      # are 1-10.
      attr_accessor :number_of_workers

      #
      # Validate the object. Throws ValidationError if validation fails.
      #
      def validate
      end

      #
      # Serializes given Model object into Ruby Hash.
      # @param object Model object to serialize.
      # @return [Hash] Serialized object in form of Ruby Hash.
      #
      def self.serialize_object(output_object, object)
        Azure::ARM::TypeBase.serialize_object(output_object, object)
        object.validate

        serialized_property = object.name
        output_object[:name] = serialized_property unless serialized_property.nil?

        serialized_property = object.number_of_workers
        if serialized_property.is_a? Azure::ARM::Expression
          unless serialized_property.nil?
            serialized_property = serialized_property.to_s
          end
        end
        output_object[:numberOfWorkers] = serialized_property unless serialized_property.nil?

        output_object
      end

      def to_h
        hash = {}
        ServerfarmsProperties.serialize_object(hash,self)
        hash
      end

      def self.ds_properties
        result = Array.new 
        result.push :number_of_workers
        result
      end

      #
      # Deserializes given Ruby Hash into Model object.
      # @param object [Hash] Ruby Hash object to deserialize.
      # @return [ServerfarmsProperties] Deserialized object.
      #
      def self.deserialize_object(output_object, object)
        return if object.nil?
        conf = Configurator.new
        conf.parent = output_object

        if object.key?(:name)
          conf.name object[:name]
          object.delete :name
        end

        if object.key?(:number_of_workers)
          conf.number_of_workers object[:number_of_workers]
          object.delete :number_of_workers
        end

        output_object
      end

      def get_name_template
        'sp'
        end

      def initialize(parent, init)
        super(parent)
        if init.is_a? Hash
          ServerfarmsProperties.deserialize_object self, init.clone
        end
      end

      # Configuration code
      class Configurator < Azure::ARM::ResourceConfigurator
        attr_accessor :parent
        # @param name
        #        String
        def name(props)
          if props.is_a? String or props.is_a? Azure::ARM::Expression
            @parent.name = props
            return
          end
          @parent.name
        end
        # @param number_of_workers
        #        Fixnum
        #        Expression
        def number_of_workers(props)
          if props.is_a? Fixnum or props.is_a? Azure::ARM::Expression
            @parent.number_of_workers = props
            return
          end
          if @parent.number_of_workers.nil? and props.is_a? Azure::ARM::Expression
            @parent.number_of_workers = props
          end
          @parent.number_of_workers
        end
        def create(init=nil,&block)
          @parent = ServerfarmsProperties.new nil, init
          self.instance_exec(@parent,&block) if block
          @parent
        end
      end
      def configure(&block)
        conf = Configurator.new
        conf.parent = self
        conf.instance_exec(self,&block) if block
        self
      end
    end
end
