# encoding: utf-8
# Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.

require_relative '../arm/module_definition'
require_relative './module_definition'

module Azure::ARM::Web
    #
    # Microsoft.Web/serverfarms
    #
    class Serverfarm < Azure::ARM::ResourceBase

      # @return Microsoft.Web/serverfarms: Server farm sku.
      attr_accessor :sku

      # @return [ServerfarmsProperties]
      attr_accessor :properties

      #
      # Validate the object. Throws ValidationError if validation fails.
      #
      def validate
        fail ArgumentError, 'property type is nil' if self.type.nil?
        fail ArgumentError, 'property api_version is nil' if self.api_version.nil?
        fail ArgumentError, 'property properties is nil' if self.properties.nil?
        @properties.validate unless @properties.nil?
      end

      #
      # Serializes given Model object into Ruby Hash.
      # @param object Model object to serialize.
      # @return [Hash] Serialized object in form of Ruby Hash.
      #
      def self.serialize_object(output_object, object)
        Azure::ARM::ResourceBase.serialize_object(output_object, object)
        object.validate

        serialized_property = object.properties
        unless serialized_property.nil?
          serialized_property = serialized_property.to_h
        end
        output_object[:properties] = serialized_property unless serialized_property.nil?

        serialized_property = object.sku
        if serialized_property.is_a? ServerfarmsSku0
          unless serialized_property.nil?
            serialized_property = serialized_property.to_h
          end
        end
        if serialized_property.is_a? Azure::ARM::Expression
          unless serialized_property.nil?
            serialized_property = serialized_property.to_s
          end
        end
        output_object[:sku] = serialized_property unless serialized_property.nil?

        output_object
      end

      def to_h
        self.validate
        hash = {}
        Serverfarm.serialize_object(hash,self)
        hash
      end

      def self.ds_properties
        result = Array.new
        result.push :sku
        result.push :properties
        result
      end

      #
      # Deserializes given Ruby Hash into Model object.
      # @param object [Hash] Ruby Hash object to deserialize.
      # @return [Serverfarm] Deserialized object.
      #
      def self.deserialize_object(output_object, object)
        return if object.nil?
        object.delete :name
        object.delete :type
        object.delete :api_version
        object.delete :location
        object.delete :tags
        object.delete :copy
        object.delete :comments
        conf = Configurator.new output_object.template
        conf.parent = output_object

        if object.key?(:properties)
          conf.properties object[:properties]
        end

        if object.key?(:sku)
          conf.sku object[:sku]
          object.delete :sku
        end

        unless object.key?(:properties)
          conf.properties object
        end

        output_object
      end

      def get_name_template
        's'
      end

      def initialize(parent, init)
        super(parent, init)
        self.type = 'Microsoft.Web/serverfarms' if self.type.nil?
        self.api_version = '2015-08-01' if self.api_version.nil?
        if init.is_a? Hash
          Serverfarm.deserialize_object self, init.clone
        end 
      end

      # Configuration code
      class Configurator < Azure::ARM::ResourceConfigurator
        attr_accessor :parent
        attr_accessor :template
        # @param sku
        #        ServerfarmsSku0
        #        Expression
        def sku(props)
          if @parent.sku.nil? and props.is_a? ServerfarmsSku0
            @parent.sku = props
            @parent.sku.parent = @parent
            @parent.sku._rsrcpath = 'sku'
          end
          if @parent.sku.nil? and (props.is_a? Hash) and (Azure::ARM::TypeBase.matches_type props, ServerfarmsSku0)
            @parent.sku = ServerfarmsSku0.new(@parent, props)
            @parent.sku._rsrcpath = 'sku'
          end
          if @parent.sku.nil? and props.is_a? Azure::ARM::Expression
            @parent.sku = props
          end
          @parent.sku
        end
        # @param properties
        #        ServerfarmsProperties
        def properties(props)
          if @parent.properties.nil? and props.is_a? ServerfarmsProperties
            @parent.properties = props
            @parent.properties.parent = @parent
            @parent.properties._rsrcpath = 'properties'
          end
          if @parent.properties.nil? and (props.is_a? Hash) and (Azure::ARM::TypeBase.matches_type props, ServerfarmsProperties)
            @parent.properties = ServerfarmsProperties.new(@parent, props)
            @parent.properties._rsrcpath = 'properties'
          end
          @parent.properties
        end
        # @param name
        #        String
        def name(props)
          @parent.properties = (ServerfarmsProperties.new @parent, nil) if @parent.properties.nil?
          if props.is_a? String or props.is_a? Azure::ARM::Expression
            @parent.properties.name = props
            return
          end
          @parent.properties.name
        end
        # @param number_of_workers
        #        Fixnum
        #        Expression
        def number_of_workers(props)
          @parent.properties = (ServerfarmsProperties.new @parent, nil) if @parent.properties.nil?
          if props.is_a? Fixnum or props.is_a? Azure::ARM::Expression
            @parent.properties.number_of_workers = props
            return
          end
          if @parent.properties.number_of_workers.nil? and props.is_a? Azure::ARM::Expression
            @parent.properties.number_of_workers = props
          end
          @parent.properties.number_of_workers
        end
        def initialize(template)
          @template = template
        end
        def create(init=nil,&block)
          @parent = Serverfarm.new @template,init
          @template.resources.push @parent
          self.instance_exec(@parent,&block) if block
          @parent
        end
      end
      def configure(&block)
        conf = Configurator.new self.template
        conf.parent = self
        conf.instance_exec(self,&block) if block
        self
      end
    end
end
