# encoding: utf-8
# Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.

require_relative '../arm/module_definition'
require_relative './module_definition'

module Azure::ARM::Web
    #
    # Model object.
    #
    class WebProperties < Azure::ARM::TypeBase

      # @return [String] Microsoft.Web/sites/config: PHP version (an empty
      # string disables PHP).
      attr_accessor :php_version

      # @return [String] Microsoft.Web/sites/config: The .Net Framework
      # version.
      attr_accessor :net_framework_version

      #
      # Validate the object. Throws ValidationError if validation fails.
      #
      def validate
        # Nothing to validate
      end

      #
      # Serializes given Model object into Ruby Hash.
      # @param object Model object to serialize.
      # @return [Hash] Serialized object in form of Ruby Hash.
      #
      def self.serialize_object(output_object, object)
        Azure::ARM::TypeBase.serialize_object(output_object, object)
        object.validate

        serialized_property = object.php_version
        output_object[:phpVersion] = serialized_property unless serialized_property.nil?

        serialized_property = object.net_framework_version
        output_object[:netFrameworkVersion] = serialized_property unless serialized_property.nil?

        output_object
      end

      def to_h
        hash = {}
        WebProperties.serialize_object(hash,self)
        hash
      end

      def self.ds_properties
        result = Array.new 
        result.push :php_version
        result.push :net_framework_version
        result
      end

      #
      # Deserializes given Ruby Hash into Model object.
      # @param object [Hash] Ruby Hash object to deserialize.
      # @return [WebProperties] Deserialized object.
      #
      def self.deserialize_object(output_object, object)
        return if object.nil?
        conf = Configurator.new
        conf.parent = output_object

        if object.key?(:php_version)
          conf.php_version object[:php_version]
          object.delete :php_version
        end

        if object.key?(:net_framework_version)
          conf.net_framework_version object[:net_framework_version]
          object.delete :net_framework_version
        end

        output_object
      end

      def get_name_template
        'wp'
        end

      def initialize(parent, init)
        super(parent)
        if init.is_a? Hash
          WebProperties.deserialize_object self, init.clone
        end
      end

      # Configuration code
      class Configurator < Azure::ARM::ResourceConfigurator
        attr_accessor :parent
        # @param php_version
        #        String
        def php_version(props)
          if props.is_a? String or props.is_a? Azure::ARM::Expression
            @parent.php_version = props
            return
          end
          @parent.php_version
        end
        # @param net_framework_version
        #        String
        def net_framework_version(props)
          if props.is_a? String or props.is_a? Azure::ARM::Expression
            @parent.net_framework_version = props
            return
          end
          @parent.net_framework_version
        end
        def create(init=nil,&block)
          @parent = WebProperties.new nil, init
          self.instance_exec(@parent,&block) if block
          @parent
        end
      end
      def configure(&block)
        conf = Configurator.new
        conf.parent = self
        conf.instance_exec(self,&block) if block
        self
      end
    end
end
